// Generated by generate-pilot-routing.mjs; contains routing metadata only.
import type { AnyContractRouter } from '@orpc/contract';

export default {
	"instance": {
		"serverInfo": {
			"~orpc": {
				"errorMap": {},
				"meta": {
					"requestName": "server-info"
				},
				"route": {
					"method": "POST",
					"path": "/server-info",
					"operationId": "post___server-info",
					"tags": [
						"meta"
					]
				}
			}
		},
		"serverInfoGet": {
			"~orpc": {
				"errorMap": {},
				"meta": {},
				"route": {
					"method": "GET",
					"path": "/server-info",
					"operationId": "get___server-info",
					"tags": [
						"meta"
					]
				}
			}
		}
	},
	"notes": {
		"delete": {
			"~orpc": {
				"errorMap": {},
				"meta": {
					"requestName": "notes/delete"
				},
				"route": {
					"method": "POST",
					"path": "/notes/delete",
					"operationId": "post___notes___delete",
					"tags": [
						"notes"
					],
					"description": "Delete a note. Requires write:notes permission.",
					"successStatus": 204
				}
			}
		}
	},
	"drive": {
		"files": {
			"create": {
				"~orpc": {
					"errorMap": {},
					"meta": {
						"requestName": "drive/files/create"
					},
					"route": {
						"method": "POST",
						"path": "/drive/files/create",
						"operationId": "post___drive___files___create",
						"tags": [
							"drive"
						],
						"description": "Upload a new drive file. Requires write:drive permission."
					}
				}
			}
		}
	}
} satisfies AnyContractRouter;
