// Generated by generate-pilot-routing.mjs; contains routing and declared-error status metadata only.
import type { AnyContractRouter } from '@orpc/contract';

export default {
	"instance": {
		"serverInfo": {
			"~orpc": {
				"errorMap": {
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "server-info"
				},
				"route": {
					"method": "POST",
					"path": "/server-info",
					"operationId": "post___server-info",
					"tags": [
						"meta"
					]
				}
			}
		},
		"serverInfoGet": {
			"~orpc": {
				"errorMap": {
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {},
				"route": {
					"method": "GET",
					"path": "/server-info",
					"operationId": "get___server-info",
					"tags": [
						"meta"
					]
				}
			}
		}
	},
	"notes": {
		"delete": {
			"~orpc": {
				"errorMap": {
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_NOTE": {
						"status": 400
					},
					"ACCESS_DENIED": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "notes/delete"
				},
				"route": {
					"method": "POST",
					"path": "/notes/delete",
					"operationId": "post___notes___delete",
					"tags": [
						"notes"
					],
					"description": "Delete a note. Requires write:notes permission.",
					"successStatus": 204
				}
			}
		}
	},
	"drive": {
		"files": {
			"create": {
				"~orpc": {
					"errorMap": {
						"AUTHENTICATION_FAILED": {
							"status": 401
						},
						"CREDENTIAL_REQUIRED": {
							"status": 401
						},
						"YOUR_ACCOUNT_SUSPENDED": {
							"status": 403
						},
						"YOUR_ACCOUNT_MOVED": {
							"status": 403
						},
						"PERMISSION_DENIED": {
							"status": 403
						},
						"RATE_LIMIT_EXCEEDED": {
							"status": 429
						},
						"INVALID_PARAM": {
							"status": 400
						},
						"INTERNAL_ERROR": {
							"status": 500
						},
						"FILE_REQUIRED": {
							"status": 400
						},
						"INVALID_FILE_NAME": {
							"status": 400
						},
						"INAPPROPRIATE": {
							"status": 400
						},
						"NO_FREE_SPACE": {
							"status": 400
						},
						"MAX_FILE_SIZE_EXCEEDED": {
							"status": 413
						},
						"UNALLOWED_FILE_TYPE": {
							"status": 400
						}
					},
					"meta": {
						"requestName": "drive/files/create"
					},
					"route": {
						"method": "POST",
						"path": "/drive/files/create",
						"operationId": "post___drive___files___create",
						"tags": [
							"drive"
						],
						"description": "Upload a new drive file. Requires write:drive permission."
					}
				}
			}
		}
	}
} satisfies AnyContractRouter;
