// Generated by generate-pilot-routing.mjs; contains routing and declared-error status metadata only.
import type { AnyContractRouter } from '@orpc/contract';

export default {
	"instance": {
		"serverInfo": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "server-info",
					"allowGet": true,
					"cacheSec": 60
				},
				"route": {
					"method": "POST",
					"path": "/server-info",
					"operationId": "post___server-info",
					"tags": [
						"meta"
					]
				}
			}
		},
		"serverInfoGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {},
				"route": {
					"method": "GET",
					"path": "/server-info",
					"operationId": "get___server-info",
					"tags": [
						"meta"
					]
				}
			}
		},
		"adCreate": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/ad/create",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/admin/ad/create",
					"operationId": "post___admin___ad___create",
					"tags": [
						"admin"
					]
				}
			}
		},
		"adDelete": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_AD": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/ad/delete",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/admin/ad/delete",
					"operationId": "post___admin___ad___delete",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"adList": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/ad/list",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/admin/ad/list",
					"operationId": "post___admin___ad___list",
					"tags": [
						"admin"
					]
				}
			}
		},
		"adUpdate": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_AD": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/ad/update",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/admin/ad/update",
					"operationId": "post___admin___ad___update",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"adminMeta": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/meta",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/admin/meta",
					"operationId": "post___admin___meta",
					"tags": [
						"meta"
					]
				}
			}
		},
		"adminServerInfo": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/server-info",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/admin/server-info",
					"operationId": "post___admin___server-info",
					"tags": [
						"admin",
						"meta"
					]
				}
			}
		},
		"updateMeta": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/update-meta",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/admin/update-meta",
					"operationId": "post___admin___update-meta",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"endpoint": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "endpoint",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/endpoint",
					"operationId": "post___endpoint",
					"tags": [
						"meta"
					]
				}
			}
		},
		"endpoints": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "endpoints",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/endpoints",
					"operationId": "post___endpoints",
					"tags": [
						"meta"
					]
				}
			}
		},
		"onlineUsersCount": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "get-online-users-count",
					"allowGet": true,
					"cacheSec": 60
				},
				"route": {
					"method": "POST",
					"path": "/get-online-users-count",
					"operationId": "post___get-online-users-count",
					"tags": [
						"meta"
					]
				}
			}
		},
		"onlineUsersCountGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"cacheSec": 60
				},
				"route": {
					"method": "GET",
					"path": "/get-online-users-count",
					"operationId": "get___get-online-users-count",
					"tags": [
						"meta"
					]
				}
			}
		},
		"meta": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "meta",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/meta",
					"operationId": "post___meta",
					"tags": [
						"meta"
					]
				}
			}
		},
		"ping": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "ping",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/ping",
					"operationId": "post___ping",
					"tags": [
						"meta"
					]
				}
			}
		},
		"pinnedUsers": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "pinned-users",
					"allowGet": false
				},
				"route": {
					"method": "POST",
					"path": "/pinned-users",
					"operationId": "post___pinned-users",
					"tags": [
						"users"
					]
				}
			}
		}
	},
	"statistics": {
		"activeUsers": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/active-users",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/active-users",
					"operationId": "post___charts___active-users",
					"tags": [
						"charts",
						"users"
					]
				}
			}
		},
		"activeUsersGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/active-users",
					"operationId": "get___charts___active-users",
					"tags": [
						"charts",
						"users"
					]
				}
			}
		},
		"apRequest": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/ap-request",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/ap-request",
					"operationId": "post___charts___ap-request",
					"tags": [
						"charts"
					]
				}
			}
		},
		"apRequestGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/ap-request",
					"operationId": "get___charts___ap-request",
					"tags": [
						"charts"
					]
				}
			}
		},
		"drive": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/drive",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/drive",
					"operationId": "post___charts___drive",
					"tags": [
						"charts",
						"drive"
					]
				}
			}
		},
		"driveGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/drive",
					"operationId": "get___charts___drive",
					"tags": [
						"charts",
						"drive"
					]
				}
			}
		},
		"federation": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/federation",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/federation",
					"operationId": "post___charts___federation",
					"tags": [
						"charts"
					]
				}
			}
		},
		"federationGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/federation",
					"operationId": "get___charts___federation",
					"tags": [
						"charts"
					]
				}
			}
		},
		"instance": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/instance",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/instance",
					"operationId": "post___charts___instance",
					"tags": [
						"charts"
					]
				}
			}
		},
		"instanceGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/instance",
					"operationId": "get___charts___instance",
					"tags": [
						"charts"
					]
				}
			}
		},
		"notes": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/notes",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/notes",
					"operationId": "post___charts___notes",
					"tags": [
						"charts",
						"notes"
					]
				}
			}
		},
		"notesGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/notes",
					"operationId": "get___charts___notes",
					"tags": [
						"charts",
						"notes"
					]
				}
			}
		},
		"userDrive": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/user/drive",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/user/drive",
					"operationId": "post___charts___user___drive",
					"tags": [
						"charts",
						"drive",
						"users"
					]
				}
			}
		},
		"userDriveGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/user/drive",
					"operationId": "get___charts___user___drive",
					"tags": [
						"charts",
						"drive",
						"users"
					]
				}
			}
		},
		"userFollowing": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/user/following",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/user/following",
					"operationId": "post___charts___user___following",
					"tags": [
						"charts",
						"users",
						"following"
					]
				}
			}
		},
		"userFollowingGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/user/following",
					"operationId": "get___charts___user___following",
					"tags": [
						"charts",
						"users",
						"following"
					]
				}
			}
		},
		"userNotes": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/user/notes",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/user/notes",
					"operationId": "post___charts___user___notes",
					"tags": [
						"charts",
						"users",
						"notes"
					]
				}
			}
		},
		"userNotesGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/user/notes",
					"operationId": "get___charts___user___notes",
					"tags": [
						"charts",
						"users",
						"notes"
					]
				}
			}
		},
		"userPv": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/user/pv",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/user/pv",
					"operationId": "post___charts___user___pv",
					"tags": [
						"charts",
						"users"
					]
				}
			}
		},
		"userPvGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/user/pv",
					"operationId": "get___charts___user___pv",
					"tags": [
						"charts",
						"users"
					]
				}
			}
		},
		"userReactions": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/user/reactions",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/user/reactions",
					"operationId": "post___charts___user___reactions",
					"tags": [
						"charts",
						"users",
						"reactions"
					]
				}
			}
		},
		"userReactionsGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/user/reactions",
					"operationId": "get___charts___user___reactions",
					"tags": [
						"charts",
						"users",
						"reactions"
					]
				}
			}
		},
		"users": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "charts/users",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/charts/users",
					"operationId": "post___charts___users",
					"tags": [
						"charts",
						"users"
					]
				}
			}
		},
		"usersGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/charts/users",
					"operationId": "get___charts___users",
					"tags": [
						"charts",
						"users"
					]
				}
			}
		},
		"retention": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "retention",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/retention",
					"operationId": "post___retention",
					"tags": [
						"users"
					]
				}
			}
		},
		"retentionGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/retention",
					"operationId": "get___retention",
					"tags": [
						"users"
					]
				}
			}
		},
		"stats": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "stats"
				},
				"route": {
					"method": "POST",
					"path": "/stats",
					"operationId": "post___stats",
					"tags": [
						"meta"
					]
				}
			}
		}
	},
	"discovery": {
		"hashtags/list": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "hashtags/list"
				},
				"route": {
					"method": "POST",
					"path": "/hashtags/list",
					"operationId": "post___hashtags___list",
					"tags": [
						"hashtags"
					]
				}
			}
		},
		"hashtags/search": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "hashtags/search"
				},
				"route": {
					"method": "POST",
					"path": "/hashtags/search",
					"operationId": "post___hashtags___search",
					"tags": [
						"hashtags"
					]
				}
			}
		},
		"hashtags/show": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_HASHTAG": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "hashtags/show"
				},
				"route": {
					"method": "POST",
					"path": "/hashtags/show",
					"operationId": "post___hashtags___show",
					"tags": [
						"hashtags"
					]
				}
			}
		},
		"hashtags/trend": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "hashtags/trend",
					"allowGet": true,
					"cacheSec": 60
				},
				"route": {
					"method": "POST",
					"path": "/hashtags/trend",
					"operationId": "post___hashtags___trend",
					"tags": [
						"hashtags"
					]
				}
			}
		},
		"hashtags/trend:get": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {},
				"route": {
					"method": "GET",
					"path": "/hashtags/trend",
					"operationId": "get___hashtags___trend",
					"tags": [
						"hashtags"
					]
				}
			}
		},
		"hashtags/users": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "hashtags/users"
				},
				"route": {
					"method": "POST",
					"path": "/hashtags/users",
					"operationId": "post___hashtags___users",
					"tags": [
						"hashtags",
						"users"
					]
				}
			}
		},
		"notes/featured": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "notes/featured",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/notes/featured",
					"operationId": "post___notes___featured",
					"tags": [
						"notes"
					]
				}
			}
		},
		"notes/featured:get": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {},
				"route": {
					"method": "GET",
					"path": "/notes/featured",
					"operationId": "get___notes___featured",
					"tags": [
						"notes"
					]
				}
			}
		},
		"notes/search-by-tag": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "notes/search-by-tag"
				},
				"route": {
					"method": "POST",
					"path": "/notes/search-by-tag",
					"operationId": "post___notes___search-by-tag",
					"tags": [
						"notes",
						"hashtags"
					]
				}
			}
		},
		"users/featured-notes": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "users/featured-notes",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/users/featured-notes",
					"operationId": "post___users___featured-notes",
					"tags": [
						"notes"
					]
				}
			}
		},
		"users/featured-notes:get": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {},
				"route": {
					"method": "GET",
					"path": "/users/featured-notes",
					"operationId": "get___users___featured-notes",
					"tags": [
						"notes"
					]
				}
			}
		},
		"users/get-frequently-replied-users": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_USER": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "users/get-frequently-replied-users"
				},
				"route": {
					"method": "POST",
					"path": "/users/get-frequently-replied-users",
					"operationId": "post___users___get-frequently-replied-users",
					"tags": [
						"users"
					],
					"description": "Get a list of other users that the specified user frequently replies to."
				}
			}
		},
		"users/recommendation": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "users/recommendation"
				},
				"route": {
					"method": "POST",
					"path": "/users/recommendation",
					"operationId": "post___users___recommendation",
					"tags": [
						"users"
					],
					"description": "Show users that the authenticated user might be interested to follow."
				}
			}
		},
		"users/search": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "users/search"
				},
				"route": {
					"method": "POST",
					"path": "/users/search",
					"operationId": "post___users___search",
					"tags": [
						"users"
					],
					"description": "Search for users."
				}
			}
		},
		"users/search-by-username-and-host": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "users/search-by-username-and-host"
				},
				"route": {
					"method": "POST",
					"path": "/users/search-by-username-and-host",
					"operationId": "post___users___search-by-username-and-host",
					"tags": [
						"users"
					],
					"description": "Search for a user by username and/or host."
				}
			}
		}
	},
	"announcements": {
		"create": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/announcements/create"
				},
				"route": {
					"method": "POST",
					"path": "/admin/announcements/create",
					"operationId": "post___admin___announcements___create",
					"tags": [
						"admin"
					]
				}
			}
		},
		"delete": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_ANNOUNCEMENT": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/announcements/delete"
				},
				"route": {
					"method": "POST",
					"path": "/admin/announcements/delete",
					"operationId": "post___admin___announcements___delete",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"adminList": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/announcements/list"
				},
				"route": {
					"method": "POST",
					"path": "/admin/announcements/list",
					"operationId": "post___admin___announcements___list",
					"tags": [
						"admin"
					]
				}
			}
		},
		"update": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_ANNOUNCEMENT": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/announcements/update"
				},
				"route": {
					"method": "POST",
					"path": "/admin/announcements/update",
					"operationId": "post___admin___announcements___update",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"list": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "announcements"
				},
				"route": {
					"method": "POST",
					"path": "/announcements",
					"operationId": "post___announcements",
					"tags": [
						"meta"
					]
				}
			}
		},
		"show": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_ANNOUNCEMENT": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "announcements/show"
				},
				"route": {
					"method": "POST",
					"path": "/announcements/show",
					"operationId": "post___announcements___show",
					"tags": [
						"meta"
					]
				}
			}
		},
		"read": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/read-announcement"
				},
				"route": {
					"method": "POST",
					"path": "/i/read-announcement",
					"operationId": "post___i___read-announcement",
					"tags": [
						"account"
					],
					"successStatus": 204
				}
			}
		}
	},
	"avatarDecorations": {
		"create": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/avatar-decorations/create"
				},
				"route": {
					"method": "POST",
					"path": "/admin/avatar-decorations/create",
					"operationId": "post___admin___avatar-decorations___create",
					"tags": [
						"admin"
					]
				}
			}
		},
		"delete": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/avatar-decorations/delete"
				},
				"route": {
					"method": "POST",
					"path": "/admin/avatar-decorations/delete",
					"operationId": "post___admin___avatar-decorations___delete",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"list": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/avatar-decorations/list"
				},
				"route": {
					"method": "POST",
					"path": "/admin/avatar-decorations/list",
					"operationId": "post___admin___avatar-decorations___list",
					"tags": [
						"admin"
					]
				}
			}
		},
		"update": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/avatar-decorations/update"
				},
				"route": {
					"method": "POST",
					"path": "/admin/avatar-decorations/update",
					"operationId": "post___admin___avatar-decorations___update",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"get": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "get-avatar-decorations"
				},
				"route": {
					"method": "POST",
					"path": "/get-avatar-decorations",
					"operationId": "post___get-avatar-decorations",
					"tags": [
						"users"
					]
				}
			}
		}
	},
	"preferences": {
		"get": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_KEY": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "i/registry/get"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/get",
					"operationId": "post___i___registry___get",
					"tags": [
						"account"
					]
				}
			}
		},
		"getAll": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/registry/get-all"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/get-all",
					"operationId": "post___i___registry___get-all",
					"tags": [
						"account"
					]
				}
			}
		},
		"getDetail": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_KEY": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "i/registry/get-detail"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/get-detail",
					"operationId": "post___i___registry___get-detail",
					"tags": [
						"account"
					]
				}
			}
		},
		"keys": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/registry/keys"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/keys",
					"operationId": "post___i___registry___keys",
					"tags": [
						"account"
					]
				}
			}
		},
		"keysWithType": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/registry/keys-with-type"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/keys-with-type",
					"operationId": "post___i___registry___keys-with-type",
					"tags": [
						"account"
					]
				}
			}
		},
		"remove": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_KEY": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "i/registry/remove"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/remove",
					"operationId": "post___i___registry___remove",
					"tags": [
						"account"
					],
					"successStatus": 204
				}
			}
		},
		"scopesWithDomain": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/registry/scopes-with-domain"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/scopes-with-domain",
					"operationId": "post___i___registry___scopes-with-domain",
					"tags": [
						"account"
					]
				}
			}
		},
		"set": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/registry/set"
				},
				"route": {
					"method": "POST",
					"path": "/i/registry/set",
					"operationId": "post___i___registry___set",
					"tags": [
						"account"
					],
					"successStatus": 204
				}
			}
		}
	},
	"emojis": {
		"add": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_FILE": {
						"status": 400
					},
					"UNSUPPORTED_FILE_TYPE": {
						"status": 400
					},
					"DUPLICATE_NAME": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/emoji/add"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/add",
					"operationId": "post___admin___emoji___add",
					"tags": [
						"admin"
					]
				}
			}
		},
		"addAliasesBulk": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/add-aliases-bulk"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/add-aliases-bulk",
					"operationId": "post___admin___emoji___add-aliases-bulk",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"copy": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_EMOJI": {
						"status": 400
					},
					"DUPLICATE_NAME": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/emoji/copy"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/copy",
					"operationId": "post___admin___emoji___copy",
					"tags": [
						"admin"
					]
				}
			}
		},
		"delete": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_EMOJI": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/emoji/delete"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/delete",
					"operationId": "post___admin___emoji___delete",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"deleteBulk": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/delete-bulk"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/delete-bulk",
					"operationId": "post___admin___emoji___delete-bulk",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"importZip": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/import-zip"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/import-zip",
					"operationId": "post___admin___emoji___import-zip",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"list": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/list"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/list",
					"operationId": "post___admin___emoji___list",
					"tags": [
						"admin"
					]
				}
			}
		},
		"listRemote": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/list-remote"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/list-remote",
					"operationId": "post___admin___emoji___list-remote",
					"tags": [
						"admin"
					]
				}
			}
		},
		"removeAliasesBulk": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/remove-aliases-bulk"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/remove-aliases-bulk",
					"operationId": "post___admin___emoji___remove-aliases-bulk",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"setAliasesBulk": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/set-aliases-bulk"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/set-aliases-bulk",
					"operationId": "post___admin___emoji___set-aliases-bulk",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"setCategoryBulk": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/set-category-bulk"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/set-category-bulk",
					"operationId": "post___admin___emoji___set-category-bulk",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"setLicenseBulk": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "admin/emoji/set-license-bulk"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/set-license-bulk",
					"operationId": "post___admin___emoji___set-license-bulk",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"update": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_EMOJI": {
						"status": 400
					},
					"NO_SUCH_FILE": {
						"status": 400
					},
					"SAME_NAME_EMOJI_EXISTS": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "admin/emoji/update"
				},
				"route": {
					"method": "POST",
					"path": "/admin/emoji/update",
					"operationId": "post___admin___emoji___update",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"emoji": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "emoji",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/emoji",
					"operationId": "post___emoji",
					"tags": [
						"meta"
					]
				}
			}
		},
		"emojis": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "emojis",
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "POST",
					"path": "/emojis",
					"operationId": "post___emojis",
					"tags": [
						"meta"
					]
				}
			}
		},
		"emojiGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/emoji",
					"operationId": "get___emoji",
					"tags": [
						"meta"
					]
				}
			}
		},
		"emojisGet": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"allowGet": true,
					"cacheSec": 3600
				},
				"route": {
					"method": "GET",
					"path": "/emojis",
					"operationId": "get___emojis",
					"tags": [
						"meta"
					]
				}
			}
		},
		"exportCustomEmojis": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "export-custom-emojis"
				},
				"route": {
					"method": "POST",
					"path": "/export-custom-emojis",
					"operationId": "post___export-custom-emojis",
					"tags": [
						"admin"
					],
					"successStatus": 204
				}
			}
		},
		"v2List": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "v2/admin/emoji/list"
				},
				"route": {
					"method": "POST",
					"path": "/v2/admin/emoji/list",
					"operationId": "post___v2___admin___emoji___list",
					"tags": [
						"admin"
					]
				}
			}
		}
	},
	"notifications": {
		"list": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/notifications"
				},
				"route": {
					"method": "POST",
					"path": "/i/notifications",
					"operationId": "post___i___notifications",
					"tags": [
						"account",
						"notifications"
					]
				}
			}
		},
		"grouped": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "i/notifications-grouped"
				},
				"route": {
					"method": "POST",
					"path": "/i/notifications-grouped",
					"operationId": "post___i___notifications-grouped",
					"tags": [
						"account",
						"notifications"
					]
				}
			}
		},
		"create": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "notifications/create"
				},
				"route": {
					"method": "POST",
					"path": "/notifications/create",
					"operationId": "post___notifications___create",
					"tags": [
						"notifications"
					],
					"successStatus": 204
				}
			}
		},
		"flush": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "notifications/flush"
				},
				"route": {
					"method": "POST",
					"path": "/notifications/flush",
					"operationId": "post___notifications___flush",
					"tags": [
						"notifications",
						"account"
					],
					"successStatus": 204
				}
			}
		},
		"markAllAsRead": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "notifications/mark-all-as-read"
				},
				"route": {
					"method": "POST",
					"path": "/notifications/mark-all-as-read",
					"operationId": "post___notifications___mark-all-as-read",
					"tags": [
						"notifications",
						"account"
					],
					"successStatus": 204
				}
			}
		},
		"testNotification": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "notifications/test-notification"
				},
				"route": {
					"method": "POST",
					"path": "/notifications/test-notification",
					"operationId": "post___notifications___test-notification",
					"tags": [
						"notifications"
					],
					"successStatus": 204
				}
			}
		},
		"register": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"INVALID_ENDPOINT": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "sw/register"
				},
				"route": {
					"method": "POST",
					"path": "/sw/register",
					"operationId": "post___sw___register",
					"tags": [
						"account"
					],
					"description": "Register to receive push notifications."
				}
			}
		},
		"showRegistration": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "sw/show-registration"
				},
				"route": {
					"method": "POST",
					"path": "/sw/show-registration",
					"operationId": "post___sw___show-registration",
					"tags": [
						"account"
					],
					"description": "Check push notification registration exists."
				}
			}
		},
		"unregister": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					}
				},
				"meta": {
					"requestName": "sw/unregister"
				},
				"route": {
					"method": "POST",
					"path": "/sw/unregister",
					"operationId": "post___sw___unregister",
					"tags": [
						"account"
					],
					"description": "Unregister from receiving push notifications.",
					"successStatus": 204
				}
			}
		},
		"updateRegistration": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_REGISTRATION": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "sw/update-registration"
				},
				"route": {
					"method": "POST",
					"path": "/sw/update-registration",
					"operationId": "post___sw___update-registration",
					"tags": [
						"account"
					],
					"description": "Update push notification registration."
				}
			}
		}
	},
	"notes": {
		"delete": {
			"~orpc": {
				"errorMap": {
					"ACCESS_DENIED": {
						"status": 400
					},
					"ROLE_PERMISSION_DENIED": {
						"status": 403
					},
					"AUTHENTICATION_FAILED": {
						"status": 401
					},
					"CREDENTIAL_REQUIRED": {
						"status": 401
					},
					"YOUR_ACCOUNT_SUSPENDED": {
						"status": 403
					},
					"YOUR_ACCOUNT_MOVED": {
						"status": 403
					},
					"PERMISSION_DENIED": {
						"status": 403
					},
					"RATE_LIMIT_EXCEEDED": {
						"status": 429
					},
					"INVALID_PARAM": {
						"status": 400
					},
					"INTERNAL_ERROR": {
						"status": 500
					},
					"NO_SUCH_NOTE": {
						"status": 400
					}
				},
				"meta": {
					"requestName": "notes/delete"
				},
				"route": {
					"method": "POST",
					"path": "/notes/delete",
					"operationId": "post___notes___delete",
					"tags": [
						"notes"
					],
					"description": "Delete a note. Requires write:notes permission.",
					"successStatus": 204
				}
			}
		}
	},
	"drive": {
		"files": {
			"create": {
				"~orpc": {
					"errorMap": {
						"ACCESS_DENIED": {
							"status": 400
						},
						"ROLE_PERMISSION_DENIED": {
							"status": 403
						},
						"AUTHENTICATION_FAILED": {
							"status": 401
						},
						"CREDENTIAL_REQUIRED": {
							"status": 401
						},
						"YOUR_ACCOUNT_SUSPENDED": {
							"status": 403
						},
						"YOUR_ACCOUNT_MOVED": {
							"status": 403
						},
						"PERMISSION_DENIED": {
							"status": 403
						},
						"RATE_LIMIT_EXCEEDED": {
							"status": 429
						},
						"INVALID_PARAM": {
							"status": 400
						},
						"INTERNAL_ERROR": {
							"status": 500
						},
						"FILE_REQUIRED": {
							"status": 400
						},
						"INVALID_FILE_NAME": {
							"status": 400
						},
						"INAPPROPRIATE": {
							"status": 400
						},
						"NO_FREE_SPACE": {
							"status": 400
						},
						"MAX_FILE_SIZE_EXCEEDED": {
							"status": 413
						},
						"UNALLOWED_FILE_TYPE": {
							"status": 400
						}
					},
					"meta": {
						"requestName": "drive/files/create",
						"multipart": true
					},
					"route": {
						"method": "POST",
						"path": "/drive/files/create",
						"operationId": "post___drive___files___create",
						"tags": [
							"drive"
						],
						"description": "Upload a new drive file. Requires write:drive permission."
					}
				}
			}
		}
	}
} satisfies AnyContractRouter;
