/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import type { InferContractRouterInputs, InferContractRouterOutputs } from '@orpc/contract';
import * as v from 'valibot';
import { defineEndpointContract } from '../../api/contract/definition.js';
import { jsonObject } from '../../api/contract/json-object.js';
import { resultObject } from '../../api/contract/result-object.js';
import { packedReference } from '../../api/contract/packed-reference.js';

export const referenceAdminMetaInput = jsonObject({});
export const referenceAdminMetaOutput = resultObject({
	"cacheRemoteFiles": v.boolean(),
	"cacheRemoteSensitiveFiles": v.boolean(),
	"emailRequiredForSignup": v.boolean(),
	"enableHcaptcha": v.boolean(),
	"hcaptchaSiteKey": v.nullable(v.string()),
	"enableMcaptcha": v.boolean(),
	"mcaptchaSiteKey": v.nullable(v.string()),
	"mcaptchaInstanceUrl": v.nullable(v.string()),
	"enableRecaptcha": v.boolean(),
	"recaptchaSiteKey": v.nullable(v.string()),
	"enableTurnstile": v.boolean(),
	"turnstileSiteKey": v.nullable(v.string()),
	"enableTestcaptcha": v.boolean(),
	"googleAnalyticsMeasurementId": v.nullable(v.string()),
	"swPublickey": v.nullable(v.string()),
	"mascotImageUrl": v.pipe(v.nullable(v.string()), v.metadata({ "default": "/assets/ai.png" })),
	"bannerUrl": v.nullable(v.string()),
	"serverErrorImageUrl": v.nullable(v.string()),
	"infoImageUrl": v.nullable(v.string()),
	"notFoundImageUrl": v.nullable(v.string()),
	"iconUrl": v.nullable(v.string()),
	"app192IconUrl": v.nullable(v.string()),
	"app512IconUrl": v.nullable(v.string()),
	"enableEmail": v.boolean(),
	"enableServiceWorker": v.boolean(),
	"translatorAvailable": v.boolean(),
	"silencedHosts": v.exactOptional(v.array(v.string())),
	"mediaSilencedHosts": v.array(v.string()),
	"pinnedUsers": v.array(v.string()),
	"hiddenTags": v.array(v.string()),
	"blockedHosts": v.array(v.string()),
	"sensitiveWords": v.array(v.string()),
	"prohibitedWords": v.array(v.string()),
	"prohibitedWordsForNameOfUser": v.array(v.string()),
	"bannedEmailDomains": v.exactOptional(v.array(v.string())),
	"preservedUsernames": v.array(v.string()),
	"hcaptchaSecretKey": v.nullable(v.string()),
	"mcaptchaSecretKey": v.nullable(v.string()),
	"recaptchaSecretKey": v.nullable(v.string()),
	"turnstileSecretKey": v.nullable(v.string()),
	"sensitiveMediaDetection": v.picklist(["none", "all", "local", "remote"]),
	"sensitiveMediaDetectionSensitivity": v.picklist(["medium", "low", "high", "veryLow", "veryHigh"]),
	"setSensitiveFlagAutomatically": v.boolean(),
	"enableSensitiveMediaDetectionForVideos": v.boolean(),
	"sensitiveMediaDetectionApiUrl": v.nullable(v.string()),
	"sensitiveMediaDetectionApiKey": v.nullable(v.string()),
	"sensitiveMediaDetectionTimeout": v.number(),
	"sensitiveMediaDetectionMaxImagesPerRequest": v.number(),
	"proxyAccountId": v.pipe(v.string(), v.metadata({ "format": "id" })),
	"email": v.nullable(v.string()),
	"smtpSecure": v.boolean(),
	"smtpHost": v.nullable(v.string()),
	"smtpPort": v.nullable(v.number()),
	"smtpUser": v.nullable(v.string()),
	"smtpPass": v.nullable(v.string()),
	"swPrivateKey": v.nullable(v.string()),
	"useObjectStorage": v.boolean(),
	"objectStorageBaseUrl": v.nullable(v.string()),
	"objectStorageBucket": v.nullable(v.string()),
	"objectStoragePrefix": v.nullable(v.string()),
	"objectStorageEndpoint": v.nullable(v.string()),
	"objectStorageRegion": v.nullable(v.string()),
	"objectStoragePort": v.nullable(v.number()),
	"objectStorageAccessKey": v.nullable(v.string()),
	"objectStorageSecretKey": v.nullable(v.string()),
	"objectStorageUseSSL": v.boolean(),
	"objectStorageUseProxy": v.boolean(),
	"objectStorageSetPublicRead": v.boolean(),
	"enableIpLogging": v.boolean(),
	"enableActiveEmailValidation": v.boolean(),
	"enableVerifymailApi": v.boolean(),
	"verifymailAuthKey": v.nullable(v.string()),
	"enableTruemailApi": v.boolean(),
	"truemailInstance": v.nullable(v.string()),
	"truemailAuthKey": v.nullable(v.string()),
	"enableChartsForRemoteUser": v.boolean(),
	"enableChartsForFederatedInstances": v.boolean(),
	"enableStatsForFederatedInstances": v.boolean(),
	"enableServerMachineStats": v.boolean(),
	"enableIdenticonGeneration": v.boolean(),
	"manifestJsonOverride": v.string(),
	"policies": resultObject({}),
	"enableFanoutTimeline": v.boolean(),
	"enableFanoutTimelineDbFallback": v.boolean(),
	"perLocalUserUserTimelineCacheMax": v.number(),
	"perRemoteUserUserTimelineCacheMax": v.number(),
	"perUserHomeTimelineCacheMax": v.number(),
	"perUserListTimelineCacheMax": v.number(),
	"enableReactionsBuffering": v.boolean(),
	"notesPerOneAd": v.number(),
	"backgroundImageUrl": v.nullable(v.string()),
	"deeplAuthKey": v.nullable(v.string()),
	"deeplIsPro": v.boolean(),
	"defaultDarkTheme": v.nullable(v.string()),
	"defaultLightTheme": v.nullable(v.string()),
	"clientOptions": packedReference("MetaClientOptions", { legacyOutputType: 'omit' }),
	"description": v.nullable(v.string()),
	"disableRegistration": v.boolean(),
	"impressumUrl": v.nullable(v.string()),
	"maintainerEmail": v.nullable(v.string()),
	"maintainerName": v.nullable(v.string()),
	"name": v.nullable(v.string()),
	"shortName": v.nullable(v.string()),
	"objectStorageS3ForcePathStyle": v.boolean(),
	"privacyPolicyUrl": v.nullable(v.string()),
	"inquiryUrl": v.nullable(v.string()),
	"repositoryUrl": v.nullable(v.string()),
	"feedbackUrl": v.nullable(v.string()),
	"summalyProxy": v.pipe(v.nullable(v.string()), v.metadata({ "description": "[Deprecated] Use \"urlPreviewSummaryProxyUrl\" instead.", "deprecated": true })),
	"themeColor": v.nullable(v.string()),
	"tosUrl": v.nullable(v.string()),
	"uri": v.string(),
	"version": v.string(),
	"urlPreviewEnabled": v.boolean(),
	"urlPreviewAllowRedirect": v.boolean(),
	"urlPreviewTimeout": v.number(),
	"urlPreviewMaximumContentLength": v.number(),
	"urlPreviewRequireContentLength": v.boolean(),
	"urlPreviewUserAgent": v.nullable(v.string()),
	"urlPreviewSummaryProxyUrl": v.nullable(v.string()),
	"urlPreviewSensitiveList": v.array(v.string()),
	"federation": v.picklist(["all", "specified", "none"]),
	"federationHosts": v.array(v.string()),
	"deliverSuspendedSoftware": v.array(resultObject({
			"software": v.string(),
			"versionRange": v.string(),
		})),
	"singleUserMode": v.boolean(),
	"ugcVisibilityForVisitor": v.picklist(["all", "local", "none"]),
	"proxyRemoteFiles": v.boolean(),
	"signToActivityPubGet": v.boolean(),
	"allowExternalApRedirect": v.boolean(),
	"enableRemoteNotesCleaning": v.boolean(),
	"remoteNotesCleaningExpiryDaysForEachNotes": v.number(),
	"remoteNotesCleaningMaxProcessingDurationInMinutes": v.number(),
	"showRoleBadgesOfRemoteUsers": v.boolean(),
});
export const referenceAdminMetaDefinition = defineEndpointContract(
	{ method: 'POST', path: "/admin/meta", tags: ["meta"] },
	referenceAdminMetaInput,
	referenceAdminMetaOutput,
);

export const referenceEndpointDefinitions = {
	"admin/meta": referenceAdminMetaDefinition,
} as const;

export const referenceEndpointContracts = {
	"admin/meta": referenceAdminMetaDefinition.contract,
} as const;

type Inputs = InferContractRouterInputs<typeof referenceEndpointContracts>;
type Outputs = InferContractRouterOutputs<typeof referenceEndpointContracts>;
export type ReferenceEndpoints = {
	[K in keyof typeof referenceEndpointContracts]: { req: Inputs[K]; res: Outputs[K] };
};
