/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { implement } from '@orpc/server';
import type { ApiActor, ApiContext, ApiToken } from '../../api/backend/transport/context.js';
import { authentication, apiPolicy, requirePrincipal } from '../../api/backend/transport/middleware.js';
import { authContract, type AuthParsedInputs, type AuthOutputs } from './api.contract.js';
export type AuthOperations<Actor extends ApiActor> = { [Name in keyof AuthParsedInputs]: (input: AuthParsedInputs[Name], actor: Name extends 'admin/accounts/create' | 'app/create' | 'app/show' | 'auth/session/generate' | 'auth/session/show' | 'auth/session/userkey' | 'email-address/available' | 'i/revoke-token' | 'request-reset-password' | 'reset-password' | 'username/available' | 'verify-email' ? Actor | null : Actor, token: ApiToken | null, ip: string) => Promise<AuthOutputs[Name]> };
export type AuthContext<Actor extends ApiActor> = ApiContext<Actor> & { operations: { auth: AuthOperations<Actor> } };
export function createAuthRouter<Actor extends ApiActor>() {
	const api = implement(authContract, { initialInputValidationIndex: Number.POSITIVE_INFINITY }).$context<AuthContext<Actor>>().use(authentication<Actor>());
	return api.router({
		'admin/accounts/create': api['admin/accounts/create'].use(apiPolicy<Actor>({ name: 'admin/accounts/create' })).handler(({ input, context }) => context.operations.auth['admin/accounts/create'](input, context.principal, context.token, context.ip)),
		'admin/captcha/current': api['admin/captcha/current'].use(apiPolicy<Actor>({ name: 'admin/captcha/current', requireCredential: true, requireAdmin: true, kind: 'read:admin:meta' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['admin/captcha/current'](input, context.principal, context.token, context.ip)),
		'admin/captcha/save': api['admin/captcha/save'].use(apiPolicy<Actor>({ name: 'admin/captcha/save', requireCredential: true, requireAdmin: true, kind: 'write:admin:meta' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['admin/captcha/save'](input, context.principal, context.token, context.ip)),
		'admin/invite/create': api['admin/invite/create'].use(apiPolicy<Actor>({ name: 'admin/invite/create', requireCredential: true, requireModerator: true, kind: 'write:admin:invite-codes' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['admin/invite/create'](input, context.principal, context.token, context.ip)),
		'admin/invite/list': api['admin/invite/list'].use(apiPolicy<Actor>({ name: 'admin/invite/list', requireCredential: true, requireModerator: true, kind: 'read:admin:invite-codes' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['admin/invite/list'](input, context.principal, context.token, context.ip)),
		'admin/reset-password': api['admin/reset-password'].use(apiPolicy<Actor>({ name: 'admin/reset-password', requireCredential: true, requireModerator: true, kind: 'write:admin:reset-password' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['admin/reset-password'](input, context.principal, context.token, context.ip)),
		'admin/unset-mfa': api['admin/unset-mfa'].use(apiPolicy<Actor>({ name: 'admin/unset-mfa', requireCredential: true, requireModerator: true, kind: 'write:admin:unset-mfa' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['admin/unset-mfa'](input, context.principal, context.token, context.ip)),
		'app/create': api['app/create'].use(apiPolicy<Actor>({ name: 'app/create' })).handler(({ input, context }) => context.operations.auth['app/create'](input, context.principal, context.token, context.ip)),
		'app/show': api['app/show'].use(apiPolicy<Actor>({ name: 'app/show' })).handler(({ input, context }) => context.operations.auth['app/show'](input, context.principal, context.token, context.ip)),
		'auth/accept': api['auth/accept'].use(apiPolicy<Actor>({ name: 'auth/accept', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['auth/accept'](input, context.principal, context.token, context.ip)),
		'auth/session/generate': api['auth/session/generate'].use(apiPolicy<Actor>({ name: 'auth/session/generate' })).handler(({ input, context }) => context.operations.auth['auth/session/generate'](input, context.principal, context.token, context.ip)),
		'auth/session/show': api['auth/session/show'].use(apiPolicy<Actor>({ name: 'auth/session/show' })).handler(({ input, context }) => context.operations.auth['auth/session/show'](input, context.principal, context.token, context.ip)),
		'auth/session/userkey': api['auth/session/userkey'].use(apiPolicy<Actor>({ name: 'auth/session/userkey' })).handler(({ input, context }) => context.operations.auth['auth/session/userkey'](input, context.principal, context.token, context.ip)),
		'email-address/available': api['email-address/available'].use(apiPolicy<Actor>({ name: 'email-address/available' })).handler(({ input, context }) => context.operations.auth['email-address/available'](input, context.principal, context.token, context.ip)),
		'i/2fa/done': api['i/2fa/done'].use(apiPolicy<Actor>({ name: 'i/2fa/done', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/done'](input, context.principal, context.token, context.ip)),
		'i/2fa/key-done': api['i/2fa/key-done'].use(apiPolicy<Actor>({ name: 'i/2fa/key-done', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/key-done'](input, context.principal, context.token, context.ip)),
		'i/2fa/password-less': api['i/2fa/password-less'].use(apiPolicy<Actor>({ name: 'i/2fa/password-less', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/password-less'](input, context.principal, context.token, context.ip)),
		'i/2fa/register': api['i/2fa/register'].use(apiPolicy<Actor>({ name: 'i/2fa/register', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/register'](input, context.principal, context.token, context.ip)),
		'i/2fa/register-key': api['i/2fa/register-key'].use(apiPolicy<Actor>({ name: 'i/2fa/register-key', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/register-key'](input, context.principal, context.token, context.ip)),
		'i/2fa/remove-key': api['i/2fa/remove-key'].use(apiPolicy<Actor>({ name: 'i/2fa/remove-key', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/remove-key'](input, context.principal, context.token, context.ip)),
		'i/2fa/unregister': api['i/2fa/unregister'].use(apiPolicy<Actor>({ name: 'i/2fa/unregister', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/unregister'](input, context.principal, context.token, context.ip)),
		'i/2fa/update-key': api['i/2fa/update-key'].use(apiPolicy<Actor>({ name: 'i/2fa/update-key', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/2fa/update-key'](input, context.principal, context.token, context.ip)),
		'i/apps': api['i/apps'].use(apiPolicy<Actor>({ name: 'i/apps', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/apps'](input, context.principal, context.token, context.ip)),
		'i/authorized-apps': api['i/authorized-apps'].use(apiPolicy<Actor>({ name: 'i/authorized-apps', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/authorized-apps'](input, context.principal, context.token, context.ip)),
		'i/change-password': api['i/change-password'].use(apiPolicy<Actor>({ name: 'i/change-password', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/change-password'](input, context.principal, context.token, context.ip)),
		'i/regenerate-token': api['i/regenerate-token'].use(apiPolicy<Actor>({ name: 'i/regenerate-token', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/regenerate-token'](input, context.principal, context.token, context.ip)),
		'i/revoke-token': api['i/revoke-token'].use(apiPolicy<Actor>({ name: 'i/revoke-token' })).handler(({ input, context }) => context.operations.auth['i/revoke-token'](input, context.principal, context.token, context.ip)),
		'i/signin-history': api['i/signin-history'].use(apiPolicy<Actor>({ name: 'i/signin-history', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/signin-history'](input, context.principal, context.token, context.ip)),
		'i/update-email': api['i/update-email'].use(apiPolicy<Actor>({ name: 'i/update-email', requireCredential: true, secure: true, limit: {
		duration: 3600000,
		max: 3,
	} })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['i/update-email'](input, context.principal, context.token, context.ip)),
		'invite/create': api['invite/create'].use(apiPolicy<Actor>({ name: 'invite/create', requireCredential: true, kind: 'write:invite-codes', requiredRolePolicy: 'canInvite' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['invite/create'](input, context.principal, context.token, context.ip)),
		'invite/delete': api['invite/delete'].use(apiPolicy<Actor>({ name: 'invite/delete', requireCredential: true, kind: 'write:invite-codes', requiredRolePolicy: 'canInvite' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['invite/delete'](input, context.principal, context.token, context.ip)),
		'invite/limit': api['invite/limit'].use(apiPolicy<Actor>({ name: 'invite/limit', requireCredential: true, kind: 'read:invite-codes', requiredRolePolicy: 'canInvite' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['invite/limit'](input, context.principal, context.token, context.ip)),
		'invite/list': api['invite/list'].use(apiPolicy<Actor>({ name: 'invite/list', requireCredential: true, kind: 'read:invite-codes', requiredRolePolicy: 'canInvite' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['invite/list'](input, context.principal, context.token, context.ip)),
		'miauth/gen-token': api['miauth/gen-token'].use(apiPolicy<Actor>({ name: 'miauth/gen-token', requireCredential: true, secure: true })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['miauth/gen-token'](input, context.principal, context.token, context.ip)),
		'my/apps': api['my/apps'].use(apiPolicy<Actor>({ name: 'my/apps', requireCredential: true, kind: 'read:account' })).use(requirePrincipal<Actor>()).handler(({ input, context }) => context.operations.auth['my/apps'](input, context.principal, context.token, context.ip)),
		'request-reset-password': api['request-reset-password'].use(apiPolicy<Actor>({ name: 'request-reset-password', limit: {
		duration: 3600000,
		max: 3,
	} })).handler(({ input, context }) => context.operations.auth['request-reset-password'](input, context.principal, context.token, context.ip)),
		'reset-password': api['reset-password'].use(apiPolicy<Actor>({ name: 'reset-password' })).handler(({ input, context }) => context.operations.auth['reset-password'](input, context.principal, context.token, context.ip)),
		'username/available': api['username/available'].use(apiPolicy<Actor>({ name: 'username/available' })).handler(({ input, context }) => context.operations.auth['username/available'](input, context.principal, context.token, context.ip)),
		'verify-email': api['verify-email'].use(apiPolicy<Actor>({ name: 'verify-email' })).handler(({ input, context }) => context.operations.auth['verify-email'](input, context.principal, context.token, context.ip)),
	});
}
