/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { oc } from '@orpc/contract';
import * as v from 'valibot';
import { objectInput } from '../input.schema.js';
import { commonErrors } from '../../../../api/backend/transport/errors.schema.js';
import { packedMetaClientOptionsSchema } from '../meta.schema.js';
import { wireJson } from '../wire-json.schema.js';

export const adminMetaContract = oc.$meta({ requestName: 'admin/meta', allowGet: false } as const)
	.route({ method: 'POST', path: '/admin/meta', operationId: 'post___admin___meta', tags: ['meta'] })
	.errors({ ...commonErrors })
	.input(v.optional(objectInput({}), {}))
	.output(v.strictObject({
	'cacheRemoteFiles': v.boolean(),
	'cacheRemoteSensitiveFiles': v.boolean(),
	'emailRequiredForSignup': v.boolean(),
	'enableHcaptcha': v.boolean(),
	'hcaptchaSiteKey': v.nullable(v.string()),
	'enableMcaptcha': v.boolean(),
	'mcaptchaSiteKey': v.nullable(v.string()),
	'mcaptchaInstanceUrl': v.nullable(v.string()),
	'enableRecaptcha': v.boolean(),
	'recaptchaSiteKey': v.nullable(v.string()),
	'enableTurnstile': v.boolean(),
	'turnstileSiteKey': v.nullable(v.string()),
	'enableTestcaptcha': v.boolean(),
	'googleAnalyticsMeasurementId': v.nullable(v.string()),
	'swPublickey': v.nullable(v.string()),
	'mascotImageUrl': v.pipe(v.nullable(v.string()), v.metadata({ 'default': '/assets/ai.png' })),
	'bannerUrl': v.nullable(v.string()),
	'serverErrorImageUrl': v.nullable(v.string()),
	'infoImageUrl': v.nullable(v.string()),
	'notFoundImageUrl': v.nullable(v.string()),
	'iconUrl': v.nullable(v.string()),
	'app192IconUrl': v.nullable(v.string()),
	'app512IconUrl': v.nullable(v.string()),
	'enableEmail': v.boolean(),
	'enableServiceWorker': v.boolean(),
	'translatorAvailable': v.boolean(),
	'silencedHosts': v.exactOptional(v.array(v.string())),
	'mediaSilencedHosts': v.array(v.string()),
	'pinnedUsers': v.array(v.string()),
	'hiddenTags': v.array(v.string()),
	'blockedHosts': v.array(v.string()),
	'sensitiveWords': v.array(v.string()),
	'prohibitedWords': v.array(v.string()),
	'prohibitedWordsForNameOfUser': v.array(v.string()),
	'bannedEmailDomains': v.exactOptional(v.array(v.string())),
	'preservedUsernames': v.array(v.string()),
	'hcaptchaSecretKey': v.nullable(v.string()),
	'mcaptchaSecretKey': v.nullable(v.string()),
	'recaptchaSecretKey': v.nullable(v.string()),
	'turnstileSecretKey': v.nullable(v.string()),
	'sensitiveMediaDetection': v.picklist(['none', 'all', 'local', 'remote']),
	'sensitiveMediaDetectionSensitivity': v.picklist(['medium', 'low', 'high', 'veryLow', 'veryHigh']),
	'setSensitiveFlagAutomatically': v.boolean(),
	'enableSensitiveMediaDetectionForVideos': v.boolean(),
	'sensitiveMediaDetectionApiUrl': v.nullable(v.string()),
	'sensitiveMediaDetectionApiKey': v.nullable(v.string()),
	'sensitiveMediaDetectionTimeout': v.pipe(v.number(), v.finite()),
	'sensitiveMediaDetectionMaxImagesPerRequest': v.pipe(v.number(), v.finite()),
	'proxyAccountId': v.pipe(v.string(), v.metadata({ 'format': 'id' })),
	'email': v.nullable(v.string()),
	'smtpSecure': v.boolean(),
	'smtpHost': v.nullable(v.string()),
	'smtpPort': v.nullable(v.pipe(v.number(), v.finite())),
	'smtpUser': v.nullable(v.string()),
	'smtpPass': v.nullable(v.string()),
	'swPrivateKey': v.nullable(v.string()),
	'useObjectStorage': v.boolean(),
	'objectStorageBaseUrl': v.nullable(v.string()),
	'objectStorageBucket': v.nullable(v.string()),
	'objectStoragePrefix': v.nullable(v.string()),
	'objectStorageEndpoint': v.nullable(v.string()),
	'objectStorageRegion': v.nullable(v.string()),
	'objectStoragePort': v.nullable(v.pipe(v.number(), v.finite())),
	'objectStorageAccessKey': v.nullable(v.string()),
	'objectStorageSecretKey': v.nullable(v.string()),
	'objectStorageUseSSL': v.boolean(),
	'objectStorageUseProxy': v.boolean(),
	'objectStorageSetPublicRead': v.boolean(),
	'enableIpLogging': v.boolean(),
	'enableActiveEmailValidation': v.boolean(),
	'enableVerifymailApi': v.boolean(),
	'verifymailAuthKey': v.nullable(v.string()),
	'enableTruemailApi': v.boolean(),
	'truemailInstance': v.nullable(v.string()),
	'truemailAuthKey': v.nullable(v.string()),
	'enableChartsForRemoteUser': v.boolean(),
	'enableChartsForFederatedInstances': v.boolean(),
	'enableStatsForFederatedInstances': v.boolean(),
	'enableServerMachineStats': v.boolean(),
	'enableIdenticonGeneration': v.boolean(),
	'manifestJsonOverride': v.string(),
	// Instance policy rows are arbitrary keys merged with the default policy table.
	'policies': v.record(v.string(), wireJson),
	'enableFanoutTimeline': v.boolean(),
	'enableFanoutTimelineDbFallback': v.boolean(),
	'perLocalUserUserTimelineCacheMax': v.pipe(v.number(), v.finite()),
	'perRemoteUserUserTimelineCacheMax': v.pipe(v.number(), v.finite()),
	'perUserHomeTimelineCacheMax': v.pipe(v.number(), v.finite()),
	'perUserListTimelineCacheMax': v.pipe(v.number(), v.finite()),
	'enableReactionsBuffering': v.boolean(),
	'notesPerOneAd': v.pipe(v.number(), v.finite()),
	'backgroundImageUrl': v.nullable(v.string()),
	'deeplAuthKey': v.nullable(v.string()),
	'deeplIsPro': v.boolean(),
	'defaultDarkTheme': v.nullable(v.string()),
	'defaultLightTheme': v.nullable(v.string()),
	'clientOptions': packedMetaClientOptionsSchema,
	'description': v.nullable(v.string()),
	'langs': v.array(v.string()),
	'logoImageUrl': v.nullable(v.string()),
	'disableRegistration': v.boolean(),
	'impressumUrl': v.nullable(v.string()),
	'maintainerEmail': v.nullable(v.string()),
	'maintainerName': v.nullable(v.string()),
	'name': v.nullable(v.string()),
	'shortName': v.nullable(v.string()),
	'objectStorageS3ForcePathStyle': v.boolean(),
	'privacyPolicyUrl': v.nullable(v.string()),
	'inquiryUrl': v.nullable(v.string()),
	'repositoryUrl': v.nullable(v.string()),
	'feedbackUrl': v.nullable(v.string()),
	'summalyProxy': v.pipe(v.nullable(v.string()), v.metadata({ 'description': '[Deprecated] Use "urlPreviewSummaryProxyUrl" instead.', 'deprecated': true })),
	'themeColor': v.nullable(v.string()),
	'tosUrl': v.nullable(v.string()),
	'uri': v.string(),
	'version': v.string(),
	'urlPreviewEnabled': v.boolean(),
	'urlPreviewAllowRedirect': v.boolean(),
	'urlPreviewTimeout': v.pipe(v.number(), v.finite()),
	'urlPreviewMaximumContentLength': v.pipe(v.number(), v.finite()),
	'urlPreviewRequireContentLength': v.boolean(),
	'urlPreviewUserAgent': v.nullable(v.string()),
	'urlPreviewSummaryProxyUrl': v.nullable(v.string()),
	'urlPreviewSensitiveList': v.array(v.string()),
	'federation': v.picklist(['all', 'specified', 'none']),
	'federationHosts': v.array(v.string()),
	'deliverSuspendedSoftware': v.array(v.strictObject({
		'software': v.string(),
		'versionRange': v.string(),
	})),
	'singleUserMode': v.boolean(),
	'ugcVisibilityForVisitor': v.picklist(['all', 'local', 'none']),
	'proxyRemoteFiles': v.boolean(),
	'signToActivityPubGet': v.boolean(),
	'allowExternalApRedirect': v.boolean(),
	'enableRemoteNotesCleaning': v.boolean(),
	'remoteNotesCleaningExpiryDaysForEachNotes': v.pipe(v.number(), v.finite()),
	'remoteNotesCleaningMaxProcessingDurationInMinutes': v.pipe(v.number(), v.finite()),
	'showRoleBadgesOfRemoteUsers': v.boolean(),
}));
