/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { oc } from '@orpc/contract';
import * as v from 'valibot';
import { objectInput, objectInputWithRest } from '../input.schema.js';
import { wireJson } from '../wire-json.schema.js';
import { commonErrors } from '../../../../api/backend/transport/errors.schema.js';

export const updateMetaInput = objectInput({
	'disableRegistration': v.exactOptional(v.nullable(v.boolean())),
	'pinnedUsers': v.exactOptional(v.nullable(v.array(v.string()))),
	'hiddenTags': v.exactOptional(v.nullable(v.array(v.string()))),
	'blockedHosts': v.exactOptional(v.nullable(v.array(v.string()))),
	'sensitiveWords': v.exactOptional(v.nullable(v.array(v.string()))),
	'prohibitedWords': v.exactOptional(v.nullable(v.array(v.string()))),
	'prohibitedWordsForNameOfUser': v.exactOptional(v.nullable(v.array(v.string()))),
	'themeColor': v.exactOptional(v.nullable(v.pipe(v.string(), v.regex(new RegExp('^#[0-9a-fA-F]{6}$'))))),
	'mascotImageUrl': v.exactOptional(v.nullable(v.string())),
	'bannerUrl': v.exactOptional(v.nullable(v.string())),
	'serverErrorImageUrl': v.exactOptional(v.nullable(v.string())),
	'infoImageUrl': v.exactOptional(v.nullable(v.string())),
	'notFoundImageUrl': v.exactOptional(v.nullable(v.string())),
	'iconUrl': v.exactOptional(v.nullable(v.string())),
	'app192IconUrl': v.exactOptional(v.nullable(v.string())),
	'app512IconUrl': v.exactOptional(v.nullable(v.string())),
	'backgroundImageUrl': v.exactOptional(v.nullable(v.string())),
	'logoImageUrl': v.exactOptional(v.nullable(v.string())),
	'name': v.exactOptional(v.nullable(v.string())),
	'shortName': v.exactOptional(v.nullable(v.string())),
	'description': v.exactOptional(v.nullable(v.string())),
	'defaultLightTheme': v.exactOptional(v.nullable(v.string())),
	'defaultDarkTheme': v.exactOptional(v.nullable(v.string())),
	'clientOptions': v.exactOptional(v.pipe(objectInputWithRest({
		'entrancePageStyle': v.exactOptional(v.pipe(v.picklist(['classic', 'simple']), v.metadata({ 'nullable': false }))),
		'showTimelineForVisitor': v.exactOptional(v.pipe(v.boolean(), v.metadata({ 'nullable': false }))),
		'showActivitiesForVisitor': v.exactOptional(v.pipe(v.boolean(), v.metadata({ 'nullable': false }))),
	}, wireJson), v.metadata({ 'required': undefined, 'nullable': false }))),
	'cacheRemoteFiles': v.exactOptional(v.boolean()),
	'cacheRemoteSensitiveFiles': v.exactOptional(v.boolean()),
	'emailRequiredForSignup': v.exactOptional(v.boolean()),
	'enableHcaptcha': v.exactOptional(v.boolean()),
	'hcaptchaSiteKey': v.exactOptional(v.nullable(v.string())),
	'hcaptchaSecretKey': v.exactOptional(v.nullable(v.string())),
	'enableMcaptcha': v.exactOptional(v.boolean()),
	'mcaptchaSiteKey': v.exactOptional(v.nullable(v.string())),
	'mcaptchaInstanceUrl': v.exactOptional(v.nullable(v.string())),
	'mcaptchaSecretKey': v.exactOptional(v.nullable(v.string())),
	'enableRecaptcha': v.exactOptional(v.boolean()),
	'recaptchaSiteKey': v.exactOptional(v.nullable(v.string())),
	'recaptchaSecretKey': v.exactOptional(v.nullable(v.string())),
	'enableTurnstile': v.exactOptional(v.boolean()),
	'turnstileSiteKey': v.exactOptional(v.nullable(v.string())),
	'turnstileSecretKey': v.exactOptional(v.nullable(v.string())),
	'enableTestcaptcha': v.exactOptional(v.boolean()),
	'googleAnalyticsMeasurementId': v.exactOptional(v.nullable(v.string())),
	'sensitiveMediaDetection': v.exactOptional(v.picklist(['none', 'all', 'local', 'remote'])),
	'sensitiveMediaDetectionSensitivity': v.exactOptional(v.picklist(['medium', 'low', 'high', 'veryLow', 'veryHigh'])),
	'setSensitiveFlagAutomatically': v.exactOptional(v.boolean()),
	'enableSensitiveMediaDetectionForVideos': v.exactOptional(v.boolean()),
	'sensitiveMediaDetectionApiUrl': v.exactOptional(v.nullable(v.string())),
	'sensitiveMediaDetectionApiKey': v.exactOptional(v.nullable(v.string())),
	'sensitiveMediaDetectionTimeout': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer(), v.minValue(1))),
	'sensitiveMediaDetectionMaxImagesPerRequest': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer(), v.minValue(1))),
	'maintainerName': v.exactOptional(v.nullable(v.string())),
	'maintainerEmail': v.exactOptional(v.nullable(v.string())),
	'langs': v.exactOptional(v.array(v.string())),
	'deeplAuthKey': v.exactOptional(v.nullable(v.string())),
	'deeplIsPro': v.exactOptional(v.boolean()),
	'enableEmail': v.exactOptional(v.boolean()),
	'email': v.exactOptional(v.nullable(v.string())),
	'smtpSecure': v.exactOptional(v.boolean()),
	'smtpHost': v.exactOptional(v.nullable(v.string())),
	'smtpPort': v.exactOptional(v.nullable(v.pipe(v.pipe(v.number(), v.finite()), v.integer()))),
	'smtpUser': v.exactOptional(v.nullable(v.string())),
	'smtpPass': v.exactOptional(v.nullable(v.string())),
	'enableServiceWorker': v.exactOptional(v.boolean()),
	'swPublicKey': v.exactOptional(v.nullable(v.string())),
	'swPrivateKey': v.exactOptional(v.nullable(v.string())),
	'tosUrl': v.exactOptional(v.nullable(v.string())),
	'repositoryUrl': v.exactOptional(v.nullable(v.string())),
	'feedbackUrl': v.exactOptional(v.nullable(v.string())),
	'impressumUrl': v.exactOptional(v.nullable(v.string())),
	'privacyPolicyUrl': v.exactOptional(v.nullable(v.string())),
	'inquiryUrl': v.exactOptional(v.nullable(v.string())),
	'useObjectStorage': v.exactOptional(v.boolean()),
	'objectStorageBaseUrl': v.exactOptional(v.nullable(v.string())),
	'objectStorageBucket': v.exactOptional(v.nullable(v.string())),
	'objectStoragePrefix': v.exactOptional(v.nullable(v.pipe(v.string(), v.regex(new RegExp('^[a-zA-Z0-9-._]*$'))))),
	'objectStorageEndpoint': v.exactOptional(v.nullable(v.string())),
	'objectStorageRegion': v.exactOptional(v.nullable(v.string())),
	'objectStoragePort': v.exactOptional(v.nullable(v.pipe(v.pipe(v.number(), v.finite()), v.integer()))),
	'objectStorageAccessKey': v.exactOptional(v.nullable(v.string())),
	'objectStorageSecretKey': v.exactOptional(v.nullable(v.string())),
	'objectStorageUseSSL': v.exactOptional(v.boolean()),
	'objectStorageUseProxy': v.exactOptional(v.boolean()),
	'objectStorageSetPublicRead': v.exactOptional(v.boolean()),
	'objectStorageS3ForcePathStyle': v.exactOptional(v.boolean()),
	'enableIpLogging': v.exactOptional(v.boolean()),
	'enableActiveEmailValidation': v.exactOptional(v.boolean()),
	'enableVerifymailApi': v.exactOptional(v.boolean()),
	'verifymailAuthKey': v.exactOptional(v.nullable(v.string())),
	'enableTruemailApi': v.exactOptional(v.boolean()),
	'truemailInstance': v.exactOptional(v.nullable(v.string())),
	'truemailAuthKey': v.exactOptional(v.nullable(v.string())),
	'enableChartsForRemoteUser': v.exactOptional(v.boolean()),
	'enableChartsForFederatedInstances': v.exactOptional(v.boolean()),
	'enableStatsForFederatedInstances': v.exactOptional(v.boolean()),
	'enableServerMachineStats': v.exactOptional(v.boolean()),
	'enableIdenticonGeneration': v.exactOptional(v.boolean()),
	'serverRules': v.exactOptional(v.array(v.string())),
	'bannedEmailDomains': v.exactOptional(v.array(v.string())),
	'preservedUsernames': v.exactOptional(v.array(v.string())),
	'manifestJsonOverride': v.exactOptional(v.string()),
	'enableFanoutTimeline': v.exactOptional(v.boolean()),
	'enableFanoutTimelineDbFallback': v.exactOptional(v.boolean()),
	'perLocalUserUserTimelineCacheMax': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer())),
	'perRemoteUserUserTimelineCacheMax': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer())),
	'perUserHomeTimelineCacheMax': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer())),
	'perUserListTimelineCacheMax': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer())),
	'enableReactionsBuffering': v.exactOptional(v.boolean()),
	'notesPerOneAd': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer())),
	'silencedHosts': v.exactOptional(v.nullable(v.array(v.string()))),
	'mediaSilencedHosts': v.exactOptional(v.nullable(v.array(v.string()))),
	'summalyProxy': v.exactOptional(v.pipe(v.nullable(v.string()), v.metadata({ 'description': '[Deprecated] Use "urlPreviewSummaryProxyUrl" instead.' }))),
	'urlPreviewEnabled': v.exactOptional(v.boolean()),
	'urlPreviewAllowRedirect': v.exactOptional(v.boolean()),
	'urlPreviewTimeout': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer())),
	'urlPreviewMaximumContentLength': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.integer())),
	'urlPreviewRequireContentLength': v.exactOptional(v.boolean()),
	'urlPreviewUserAgent': v.exactOptional(v.nullable(v.string())),
	'urlPreviewSummaryProxyUrl': v.exactOptional(v.nullable(v.string())),
	'urlPreviewSensitiveList': v.exactOptional(v.nullable(v.array(v.string()))),
	'federation': v.exactOptional(v.picklist(['all', 'none', 'specified'])),
	'federationHosts': v.exactOptional(v.array(v.string())),
	'deliverSuspendedSoftware': v.exactOptional(v.array(objectInput({
		'software': v.string(),
		'versionRange': v.string(),
	}))),
	'singleUserMode': v.exactOptional(v.boolean()),
	'ugcVisibilityForVisitor': v.exactOptional(v.picklist(['all', 'local', 'none'])),
	'proxyRemoteFiles': v.exactOptional(v.boolean()),
	'signToActivityPubGet': v.exactOptional(v.boolean()),
	'allowExternalApRedirect': v.exactOptional(v.boolean()),
	'enableRemoteNotesCleaning': v.exactOptional(v.boolean()),
	'remoteNotesCleaningExpiryDaysForEachNotes': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.finite())),
	'remoteNotesCleaningMaxProcessingDurationInMinutes': v.exactOptional(v.pipe(v.pipe(v.number(), v.finite()), v.finite())),
	'showRoleBadgesOfRemoteUsers': v.exactOptional(v.boolean()),
});

export const updateMetaContract = oc.$meta<{ requestName: 'admin/update-meta'; allowGet: boolean; cacheSec?: number }>({ requestName: 'admin/update-meta', allowGet: false })
	.route({ method: 'POST', path: '/admin/update-meta', operationId: 'post___admin___update-meta', tags: ['admin'], successStatus: 204 })
	.errors({ ...commonErrors })
	.input(updateMetaInput)
	.output(v.void());
