<!--
SPDX-FileCopyrightText: syuilo and misskey-project
SPDX-License-Identifier: AGPL-3.0-only
-->

<template>
<PageWithHeader :actions="headerActions" :tabs="headerTabs">
	<div class="_spacer" style="--MI_SPACER-w: 900px;">
		<div class="_gaps">
			<MkPaginationControl :paginator="paginator" canFilter>
				<MkSelect v-model="type" :items="typeDef" style="margin: 0; flex: 1;">
					<template #label>{{ $locale.sfc.type }}</template>
				</MkSelect>

				<MkInput v-model="moderatorId" style="margin: 0; flex: 1;">
					<template #label>{{ $locale.sfc.moderator }}(ID)</template>
				</MkInput>
			</MkPaginationControl>

			<component :is="prefer.s.enablePullToRefresh ? MkPullToRefresh : 'div'" :refresher="() => paginator.reload()">
				<MkLoading v-if="paginator.fetching.value"/>

				<MkError v-else-if="paginator.error.value" @retry="paginator.init()"/>

				<MkTl v-else :events="timeline" groupBy="d">
					<template #left="{ event }">
						<div>
							<MkAvatar :user="event.user" style="width: 26px; height: 26px;"/>
						</div>
					</template>
					<template #right="{ event, timestamp, delta }">
						<div style="margin: 4px 0;">
							<XModLog :key="event.id" :log="event"/>
						</div>
					</template>
				</MkTl>
			</component>

			<MkButton primary rounded style="margin: 0 auto;" @click="fetchMore">{{ $locale.sfc.loadMore }}</MkButton>
		</div>
	</div>
</PageWithHeader>
</template>

<script lang="ts" setup>
import { computed, ref, markRaw, onMounted } from 'vue';
import * as Misskey from 'misskey-js';
import XModLog from '@features/moderation/frontend/pages/admin/modlog.ModLog.vue';
import MkSelect from '@features/ui/frontend/components/MkSelect.vue';
import MkInput from '@features/ui/frontend/components/MkInput.vue';
import MkTl from '@features/ui/frontend/components/MkTl.vue';
import { copyLocaleDictionary } from '@features/runtime/frontend/copy-locale-dictionary.js';
import { definePage } from '@features/navigation/frontend/page.js';
import { prefer } from '@features/preferences/frontend/preferences.js';
import { useMkSelect } from '@features/ui/frontend/composables/use-mkselect.js';
import MkPullToRefresh from '@features/ui/frontend/components/MkPullToRefresh.vue';
import MkButton from '@features/ui/frontend/components/MkButton.vue';
import MkPaginationControl from '@features/ui/frontend/components/MkPaginationControl.vue';
import { Paginator } from '@features/ui/frontend/utility/paginator.js';

const {
	model: type,
	def: typeDef,
} = useMkSelect({
	items: [
		{ label: $locale.value.sfc.all, value: null },
		...Misskey.moderationLogTypes.map(t => ({ label: copyLocaleDictionary($locale.value.sfc.moderationLogTypesLabels)[t] ?? t, value: t })),
	],
	initialValue: null,
});
const moderatorId = ref('');

const paginator = markRaw(new Paginator('admin/show-moderation-logs', {
	limit: 20,
	canFetchDetection: 'limit',
	canSearch: true,
	computedParams: computed(() => ({
		type: type.value,
		userId: moderatorId.value === '' ? null : moderatorId.value,
	})),
}));

paginator.init();

const timeline = computed(() => {
	return paginator.items.value.map(x => ({
		id: x.id,
		timestamp: new Date(x.createdAt).getTime(),
		data: x as Misskey.entities.ModerationLog,
	}));
});

function fetchMore() {
	if (paginator.order.value === 'oldest') {
		paginator.fetchNewer();
	} else {
		paginator.fetchOlder();
	}
}

const headerActions = computed(() => []);

const headerTabs = computed(() => []);

definePage(() => ({
	title: $locale.value.sfc.moderationLogs,
	icon: 'ti ti-list-search',
}));
</script>

<locale lang="json" locale="ar-SA">
{
	"type": "نوع",
	"moderator": "مشرِف",
	"loadMore": "عرض المزيد",
	"all": "الكل",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "علِق",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "حُذف الملف",
		"deleteNote": "حُذفت الملاحظة",
		"createGlobalAnnouncement": "أُنشئ إعلان عام",
		"createUserAnnouncement": "أُنشئ إعلان مستخدم",
		"updateGlobalAnnouncement": "حُدث إعلان عام",
		"updateUserAnnouncement": "حُدث إعلان مستخدم",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "أعد تعيين كلمتك السرية",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "ولِّد دعوة",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="ca-ES">
{
	"type": "Tipus",
	"moderator": "Moderador/a",
	"loadMore": "Carregar més",
	"all": "Tot",
	"moderationLogTypesLabels": {
		"clearQueue": "Esborra la cua de feina",
		"promoteQueue": "Tornar a intentar la feina de la cua",
		"createRole": "Rol creat",
		"deleteRole": "Rol esborrat",
		"updateRole": "Rol actualitzat",
		"assignRole": "Assignat al rol",
		"unassignRole": "Esborrat del rol",
		"suspend": "Suspèn",
		"unsuspend": "Suspensió treta",
		"addCustomEmoji": "Afegit emoji personalitzat",
		"updateCustomEmoji": "Actualitzat emoji personalitzat",
		"deleteCustomEmoji": "Esborrat emoji personalitzat",
		"updateServerSettings": "Configuració del servidor actualitzada",
		"updateUserNote": "Nota de moderació actualitzada",
		"deleteDriveFile": "Fitxer esborrat",
		"deleteNote": "Nota esborrada",
		"createGlobalAnnouncement": "Anunci global creat",
		"createUserAnnouncement": "Anunci individual creat",
		"updateGlobalAnnouncement": "Anunci global actualitzat",
		"updateUserAnnouncement": "Anunci individual actualitzat ",
		"deleteGlobalAnnouncement": "Anunci global esborrat",
		"deleteUserAnnouncement": "Anunci individual esborrat ",
		"resetPassword": "Restableix la contrasenya",
		"suspendRemoteInstance": "Servidor remot suspès ",
		"unsuspendRemoteInstance": "S'ha tret la suspensió del servidor remot",
		"updateRemoteInstanceNote": "Nota de moderació de la instància remota actualitzada",
		"markSensitiveDriveFile": "Fitxer marcat com a sensible",
		"unmarkSensitiveDriveFile": "S'ha tret la marca de sensible del fitxer",
		"resolveAbuseReport": "Informe resolt",
		"forwardAbuseReport": "Informe reenviat",
		"updateAbuseReportNote": "Nota de moderació d'un informe actualitzat",
		"createInvitation": "Crear codi d'invitació ",
		"createAd": "Anunci creat",
		"deleteAd": "Anunci esborrat",
		"updateAd": "Anunci actualitzat",
		"createAvatarDecoration": "Decoració de l'avatar creada",
		"updateAvatarDecoration": "S'ha actualitzat la decoració de l'avatar ",
		"deleteAvatarDecoration": "S'ha esborrat la decoració de l'avatar ",
		"unsetMfa": "Desactiva l'autenticació de dos factors per a l'usuari",
		"unsetUserAvatar": "Esborrar l'avatar d'aquest usuari",
		"unsetUserBanner": "Esborrar el bàner d'aquest usuari",
		"createSystemWebhook": "Crear un SystemWebhook",
		"updateSystemWebhook": "Actualitzar SystemWebhook",
		"deleteSystemWebhook": "Esborrar SystemWebhook",
		"createAbuseReportNotificationRecipient": "Crear un destinatari per l'informe de moderació ",
		"updateAbuseReportNotificationRecipient": "Actualitzar destinatari per l'informe de moderació ",
		"deleteAbuseReportNotificationRecipient": "Esborrar destinatari de l'informe de moderació ",
		"deleteAccount": "Esborrar el compte ",
		"deletePage": "Esborrar la pàgina",
		"deleteFlash": "Esborrar el guió",
		"deleteGalleryPost": "Esborrar la publicació de la galeria",
		"deleteChatRoom": "Esborra la sala de xat",
		"updateProxyAccountDescription": "Actualitzar descripció del compte proxy"
	},
	"moderationLogs": "Registre de moderació "
}
</locale>

<locale lang="json" locale="cs-CZ">
{
	"type": "Typ",
	"moderator": "Moderátor",
	"loadMore": "Zobrazit více",
	"all": "Vše",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Zmrazit",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Resetovat heslo",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Vygenerovat pozvánku",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="da-DK">
{
	"type": "Type",
	"moderator": "Moderator",
	"loadMore": "Load more",
	"all": "All",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Suspended",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Password reset",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="de-DE">
{
	"type": "Art",
	"moderator": "Moderator",
	"loadMore": "Mehr laden",
	"all": "Alle",
	"moderationLogTypesLabels": {
		"clearQueue": "Warteschlange leeren",
		"promoteQueue": "Warteschlange erneut ausführen",
		"createRole": "Rolle erstellt",
		"deleteRole": "Rolle gelöscht",
		"updateRole": "Rolle aktualisiert",
		"assignRole": "Zu Rolle zugewiesen",
		"unassignRole": "Aus Rolle entfernt",
		"suspend": "Gesperrt",
		"unsuspend": "Entsperrt",
		"addCustomEmoji": "Benutzerdefiniertes Emoji hinzugefügt",
		"updateCustomEmoji": "Benutzerdefiniertes Emoji aktualisiert",
		"deleteCustomEmoji": "Benutzerdefiniertes Emoji gelöscht",
		"updateServerSettings": "Servereinstellungen aktualisiert",
		"updateUserNote": "Moderationsnotiz aktualisiert",
		"deleteDriveFile": "Datei gelöscht",
		"deleteNote": "Notiz gelöscht",
		"createGlobalAnnouncement": "Globale Ankündigung erstellt",
		"createUserAnnouncement": "Benutzerspezifische Ankündigung erstellt",
		"updateGlobalAnnouncement": "Globale Ankündigung aktualisiert",
		"updateUserAnnouncement": "Benutzerspezifische Ankündigung aktualisiert",
		"deleteGlobalAnnouncement": "Globale Ankündigung gelöscht",
		"deleteUserAnnouncement": "Benutzerspezifische Ankündigung gelöscht",
		"resetPassword": "Passwort zurückgesetzt",
		"suspendRemoteInstance": "Fremde Instanz gesperrt",
		"unsuspendRemoteInstance": "Fremde Instanz entsperrt",
		"updateRemoteInstanceNote": "Aktualisierung der Moderationshinweise für fremde Server.",
		"markSensitiveDriveFile": "Datei als sensitiv markiert",
		"unmarkSensitiveDriveFile": "Datei als nicht sensitiv markiert",
		"resolveAbuseReport": "Meldung bearbeitet",
		"forwardAbuseReport": "Meldung weitergeleitet",
		"updateAbuseReportNote": "Moderationsnotiz einer Meldung aktualisiert",
		"createInvitation": "Einladung erstellt",
		"createAd": "Werbung erstellt",
		"deleteAd": "Werbung gelöscht",
		"updateAd": "Werbung aktualisiert",
		"createAvatarDecoration": "Profilbilddekoration erstellt",
		"updateAvatarDecoration": "Profilbilddekoration aktualisiert",
		"deleteAvatarDecoration": "Profilbilddekoration gelöscht",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "Profilbild zurückgesetzt",
		"unsetUserBanner": "Profilbanner zurückgesetzt",
		"createSystemWebhook": "System-Webhook erstellt",
		"updateSystemWebhook": "System-Webhook aktualisiert",
		"deleteSystemWebhook": "System-Webhook gelöscht",
		"createAbuseReportNotificationRecipient": "Empfänger für Meldungen erstellt",
		"updateAbuseReportNotificationRecipient": "Empfänger für Meldungen aktualisiert",
		"deleteAbuseReportNotificationRecipient": "Empfänger für Meldungen entfernt",
		"deleteAccount": "Benutzerkonto gelöscht",
		"deletePage": "Seite gelöscht",
		"deleteFlash": "Play gelöscht",
		"deleteGalleryPost": "Galeriebeitrag gelöscht",
		"deleteChatRoom": "Chatraum gelöscht",
		"updateProxyAccountDescription": "Beschreibung des Proxy-Benutzerkontos aktualisiert"
	},
	"moderationLogs": "Moderationsprotokolle"
}
</locale>

<locale lang="json" locale="en-US">
{
	"type": "Type",
	"moderator": "Moderator",
	"loadMore": "Load more",
	"all": "All",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Suspended",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Password reset",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="es-ES">
{
	"type": "Tipo",
	"moderator": "Moderador",
	"loadMore": "Ver más",
	"all": "Todo",
	"moderationLogTypesLabels": {
		"clearQueue": "Borrar la cola de trabajos",
		"promoteQueue": "Reintentar el trabajo en la cola",
		"createRole": "Rol creado",
		"deleteRole": "Rol eliminado",
		"updateRole": "Rol actualizado",
		"assignRole": "Rol asignado",
		"unassignRole": "Rol retirado",
		"suspend": "Suspender",
		"unsuspend": "Suspensión retirada",
		"addCustomEmoji": "Añadido emoji personalizado",
		"updateCustomEmoji": "Emoji personalizado actualizado",
		"deleteCustomEmoji": "Emoji personalizado eliminado",
		"updateServerSettings": "Ajustes de servidor actualizados",
		"updateUserNote": "Nota de moderación actualizada",
		"deleteDriveFile": "Archivo eliminado",
		"deleteNote": "Nota eliminada",
		"createGlobalAnnouncement": "Anuncio global creado",
		"createUserAnnouncement": "Anuncio de usuario creado",
		"updateGlobalAnnouncement": "Anuncio global actualizado",
		"updateUserAnnouncement": "Anuncio de usuario actualizado",
		"deleteGlobalAnnouncement": "Anuncio global eliminado",
		"deleteUserAnnouncement": "Anuncio de usuario eliminado",
		"resetPassword": "Resetear contraseña",
		"suspendRemoteInstance": "Instancia remota suspendida",
		"unsuspendRemoteInstance": "Suspensión de instancia remota retirada",
		"updateRemoteInstanceNote": "Nota de moderación de una instancia remota actualizada",
		"markSensitiveDriveFile": "Archivo marcado como sensible",
		"unmarkSensitiveDriveFile": "Archivo marcado como no sensible",
		"resolveAbuseReport": "Reporte resuelto",
		"forwardAbuseReport": "Informe reenviado",
		"updateAbuseReportNote": "Nota de moderación de un informe actualizada",
		"createInvitation": "Generar invitación",
		"createAd": "Anuncio creado",
		"deleteAd": "Anuncio eliminado",
		"updateAd": "Anuncio actualizado",
		"createAvatarDecoration": "Decoración de avatar creada",
		"updateAvatarDecoration": "Decoración de avatar actualizada",
		"deleteAvatarDecoration": "Decoración de avatar eliminada",
		"unsetMfa": "Desactivar la autenticación de dos factores del usuario",
		"unsetUserAvatar": "Quitar decoración de avatar de este usuario",
		"unsetUserBanner": "Quitar banner de este usuario",
		"createSystemWebhook": "Crear un SystemWebhook",
		"updateSystemWebhook": "Actualizar SystemWebhook ",
		"deleteSystemWebhook": "Borrar SystemWebHook",
		"createAbuseReportNotificationRecipient": "Crear un destinatario para el informe de moderación",
		"updateAbuseReportNotificationRecipient": "Destinatario de los informes actualizados",
		"deleteAbuseReportNotificationRecipient": "Destinatario de los informes borrado",
		"deleteAccount": "Cuenta Borrada",
		"deletePage": "Página borrada",
		"deleteFlash": "Juego borrado",
		"deleteGalleryPost": "Publicación de la galería, eliminada",
		"deleteChatRoom": "Borrar  sala del chat",
		"updateProxyAccountDescription": "Actualizar la descripción de la cuenta proxy"
	},
	"moderationLogs": "Log de moderación"
}
</locale>

<locale lang="json" locale="fr-FR">
{
	"type": "Type",
	"moderator": "Modérateur·rice·s",
	"loadMore": "Afficher plus …",
	"all": "Tous",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Rôle créé",
		"deleteRole": "Rôle supprimé",
		"updateRole": "Rôle mis à jour",
		"assignRole": "Rôle attribué",
		"unassignRole": "Rôle enlevé",
		"suspend": "Utilisateur suspendu",
		"unsuspend": "Suspension d'un utilisateur levée",
		"addCustomEmoji": "Émoji personnalisé ajouté",
		"updateCustomEmoji": "Émoji personnalisé mis à jour",
		"deleteCustomEmoji": "Émoji personnalisé supprimé",
		"updateServerSettings": "Paramètres du serveur mis à jour",
		"updateUserNote": "Note de modération mise à jour",
		"deleteDriveFile": "Supprimer le fichier",
		"deleteNote": "Note supprimée",
		"createGlobalAnnouncement": "Annonce globale créée",
		"createUserAnnouncement": "Annonce individuelle créée",
		"updateGlobalAnnouncement": "Annonce globale mise à jour",
		"updateUserAnnouncement": "Annonce individuelle mise à jour",
		"deleteGlobalAnnouncement": "Annonce globale supprimée",
		"deleteUserAnnouncement": "Annonce individuelle supprimée",
		"resetPassword": "Mot de passe réinitialisé",
		"suspendRemoteInstance": "Instance distante suspendue",
		"unsuspendRemoteInstance": "Suspension d'une instance distante levée",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "Fichier marqué comme sensible",
		"unmarkSensitiveDriveFile": "Marquage du fichier comme sensible enlevé",
		"resolveAbuseReport": "Signalement résolu",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Code d'invitation créé",
		"createAd": "Publicité créée",
		"deleteAd": "Publicité supprimée",
		"updateAd": "Publicité mise à jour",
		"createAvatarDecoration": "Décoration d'avatar créée",
		"updateAvatarDecoration": "Décoration d'avatar mise à jour",
		"deleteAvatarDecoration": "Décoration d'avatar supprimée",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "Supprimer l'avatar de l'utilisateur·rice",
		"unsetUserBanner": "Supprimer la bannière de l'utilisateur·rice",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Supprimer le Play",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Journal de modération"
}
</locale>

<locale lang="json" locale="id-ID">
{
	"type": "Tipe",
	"moderator": "Moderator",
	"loadMore": "Selebihnya",
	"all": "Semua",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Peran telah dibuat",
		"deleteRole": "Peran telah dihapus",
		"updateRole": "Peran telah diperbaharui",
		"assignRole": "Yang ditugaskan dalam peran",
		"unassignRole": "Dihapus dari peran",
		"suspend": "Tangguhkan",
		"unsuspend": "Batal ditangguhkan",
		"addCustomEmoji": "Emoji kustom ditambahkan",
		"updateCustomEmoji": "Emoji kustom diperbaharui",
		"deleteCustomEmoji": "Emoji kustom dihapus",
		"updateServerSettings": "Pengaturan peladen diperbaharui",
		"updateUserNote": "Catatan moderasi diperbaharui",
		"deleteDriveFile": "Berkas dihapus",
		"deleteNote": "Catatan dihapus",
		"createGlobalAnnouncement": "Pengumuman global dibuat",
		"createUserAnnouncement": "Pengumuman pengguna dibuat",
		"updateGlobalAnnouncement": "Pengumuman global diperbaharui",
		"updateUserAnnouncement": "Pengumuman pengguna diperbaharui",
		"deleteGlobalAnnouncement": "Pengumuman global telah dihapus",
		"deleteUserAnnouncement": "Pengumuman pengguna telah dihapus.",
		"resetPassword": "Atur ulang kata sandi",
		"suspendRemoteInstance": "Instansi luar telah ditangguhkan",
		"unsuspendRemoteInstance": "Instansi luar batal ditangguhkan",
		"updateRemoteInstanceNote": "Catatan moderasi telah diperbaharui untuk peladen luar.",
		"markSensitiveDriveFile": "Berkas ditandai sensitif",
		"unmarkSensitiveDriveFile": "Berkas batal ditandai sensitif",
		"resolveAbuseReport": "Laporan terselesaikan",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Buat kode undangan",
		"createAd": "Iklan telah dibuat",
		"deleteAd": "Iklan telah dihapus",
		"updateAd": "Iklan telah diperbaharui",
		"createAvatarDecoration": "Buat dekorasi avatar",
		"updateAvatarDecoration": "Perbarui dekorasi avatar",
		"deleteAvatarDecoration": "Hapus dekorasi avatar",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "Hapus avatar pengguna",
		"unsetUserBanner": "Hapus banner pengguna",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Akun dihapus",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Log moderasi"
}
</locale>

<locale lang="json" locale="it-IT">
{
	"type": "Tipo",
	"moderator": "Moderatore",
	"loadMore": "Mostra di più",
	"all": "Tutte",
	"moderationLogTypesLabels": {
		"clearQueue": "Ha cancellato la coda di Attività",
		"promoteQueue": "Ripeti le attività in coda",
		"createRole": "Crea un Ruolo",
		"deleteRole": "Elimina un Ruolo",
		"updateRole": "Modifica un ruolo",
		"assignRole": "Assegna un Ruolo",
		"unassignRole": "Toglie un Ruolo al Profilo",
		"suspend": "Sospende",
		"unsuspend": "Solleva la sospensione",
		"addCustomEmoji": "Aggiunge Emoji personalizzata",
		"updateCustomEmoji": "Modifica Emoji personalizzata",
		"deleteCustomEmoji": "Elimina Emoji personalizzata",
		"updateServerSettings": "Modifica le impostazioni del server",
		"updateUserNote": "Modifica un promemoria di moderazione",
		"deleteDriveFile": "Elimina un file dal Drive",
		"deleteNote": "Elimina una Nota",
		"createGlobalAnnouncement": "Crea un annuncio globale",
		"createUserAnnouncement": "Crea un annuncio ai profili già iscritti",
		"updateGlobalAnnouncement": "Modifica un annuncio globale",
		"updateUserAnnouncement": "Modifica un annuncio ai profili già iscritti",
		"deleteGlobalAnnouncement": "Elimina un annuncio globale",
		"deleteUserAnnouncement": "Elimina un annuncio ai profili già iscritti",
		"resetPassword": "Azzera la password",
		"suspendRemoteInstance": "Sospende una istanza remota",
		"unsuspendRemoteInstance": "Riattiva una istanza remota",
		"updateRemoteInstanceNote": "Modifica il promemoria di moderazione per il server remoto",
		"markSensitiveDriveFile": "Aggiunge NSFW a un file nel Drive",
		"unmarkSensitiveDriveFile": "Toglie NSFW da un file nel Drive",
		"resolveAbuseReport": "Risolve una segnalazione",
		"forwardAbuseReport": "Inoltra una segnalazione",
		"updateAbuseReportNote": "Modifica una segnalazione",
		"createInvitation": "Genera un codice di invito",
		"createAd": "Aggiunge un Banner",
		"deleteAd": "Elimina un Banner",
		"updateAd": "Modifica un Banner",
		"createAvatarDecoration": "Crea una decorazione della foto profilo",
		"updateAvatarDecoration": "Modifica una decorazione della foto profilo",
		"deleteAvatarDecoration": "Elimina una decorazione della foto profilo",
		"unsetMfa": "Rimossa l'autenticazione a due fattori (2FA7MFA)",
		"unsetUserAvatar": "Toglie una foto profilo",
		"unsetUserBanner": "Toglie una immagine di intestazione profilo",
		"createSystemWebhook": "Aggiunge un System Webhook",
		"updateSystemWebhook": "Modifica un System Webhook",
		"deleteSystemWebhook": "Elimina un System Webhook",
		"createAbuseReportNotificationRecipient": "Crea destinatario per le notifiche di segnalazioni",
		"updateAbuseReportNotificationRecipient": "Modifica un destinatario per le notifiche di segnalazioni",
		"deleteAbuseReportNotificationRecipient": "Elimina un destinatario per le notifiche di segnalazioni",
		"deleteAccount": "Elimina un profilo",
		"deletePage": "Elimina una Pagina",
		"deleteFlash": "Elimina un Play",
		"deleteGalleryPost": "Elimina pubblicazione nella Galleria",
		"deleteChatRoom": "Elimina una Chat",
		"updateProxyAccountDescription": "Aggiorna la descrizione del profilo proxy"
	},
	"moderationLogs": "Cronologia di moderazione"
}
</locale>

<locale lang="json" locale="ja-JP">
{
	"type": "タイプ",
	"moderator": "モデレーター",
	"loadMore": "もっと見る",
	"all": "全て",
	"moderationLogTypesLabels": {
		"clearQueue": "ジョブキューをクリア",
		"promoteQueue": "キューのジョブを再試行",
		"createRole": "ロールを作成",
		"deleteRole": "ロールを削除",
		"updateRole": "ロールを更新",
		"assignRole": "ロールへアサイン",
		"unassignRole": "ロールのアサイン解除",
		"suspend": "凍結",
		"unsuspend": "凍結解除",
		"addCustomEmoji": "カスタム絵文字追加",
		"updateCustomEmoji": "カスタム絵文字更新",
		"deleteCustomEmoji": "カスタム絵文字削除",
		"updateServerSettings": "サーバー設定更新",
		"updateUserNote": "ユーザーのモデレーションノート更新",
		"deleteDriveFile": "ファイルを削除",
		"deleteNote": "ノートを削除",
		"createGlobalAnnouncement": "全体のお知らせを作成",
		"createUserAnnouncement": "ユーザーへお知らせを作成",
		"updateGlobalAnnouncement": "全体のお知らせを更新",
		"updateUserAnnouncement": "ユーザーのお知らせを更新",
		"deleteGlobalAnnouncement": "全体のお知らせを削除",
		"deleteUserAnnouncement": "ユーザーのお知らせを削除",
		"resetPassword": "パスワードをリセット",
		"suspendRemoteInstance": "リモートサーバーを停止",
		"unsuspendRemoteInstance": "リモートサーバーを再開",
		"updateRemoteInstanceNote": "リモートサーバーのモデレーションノート更新",
		"markSensitiveDriveFile": "ファイルをセンシティブ付与",
		"unmarkSensitiveDriveFile": "ファイルをセンシティブ解除",
		"resolveAbuseReport": "通報を解決",
		"forwardAbuseReport": "通報を転送",
		"updateAbuseReportNote": "通報のモデレーションノート更新",
		"createInvitation": "招待コードを作成",
		"createAd": "広告を作成",
		"deleteAd": "広告を削除",
		"updateAd": "広告を更新",
		"createAvatarDecoration": "アイコンデコレーションを作成",
		"updateAvatarDecoration": "アイコンデコレーションを更新",
		"deleteAvatarDecoration": "アイコンデコレーションを削除",
		"unsetMfa": "ユーザーの二要素認証を解除",
		"unsetUserAvatar": "ユーザーのアイコンを解除",
		"unsetUserBanner": "ユーザーのバナーを解除",
		"createSystemWebhook": "SystemWebhookを作成",
		"updateSystemWebhook": "SystemWebhookを更新",
		"deleteSystemWebhook": "SystemWebhookを削除",
		"createAbuseReportNotificationRecipient": "通報の通知先を作成",
		"updateAbuseReportNotificationRecipient": "通報の通知先を更新",
		"deleteAbuseReportNotificationRecipient": "通報の通知先を削除",
		"deleteAccount": "アカウントを削除",
		"deletePage": "ページを削除",
		"deleteFlash": "Playを削除",
		"deleteGalleryPost": "ギャラリーの投稿を削除",
		"deleteChatRoom": "ダイレクトメッセージのグループを削除",
		"updateProxyAccountDescription": "プロキシアカウントの説明を更新"
	},
	"moderationLogs": "モデログ"
}
</locale>

<locale lang="json" locale="ja-KS">
{
	"type": "タイプ",
	"moderator": "モデレーター",
	"loadMore": "まだまだあるで！",
	"all": "みんな",
	"moderationLogTypesLabels": {
		"clearQueue": "ジョブキューをクリア",
		"promoteQueue": "キューのジョブを再試行",
		"createRole": "ロールを追加すんで",
		"deleteRole": "ロールほかす",
		"updateRole": "ロールの更新すんで",
		"assignRole": "ロールへアサイン",
		"unassignRole": "ロールのアサインほかす",
		"suspend": "凍結",
		"unsuspend": "凍結解除",
		"addCustomEmoji": "自由な絵文字追加されたで",
		"updateCustomEmoji": "自由な絵文字更新されたで",
		"deleteCustomEmoji": "自由な絵文字消されたで",
		"updateServerSettings": "サーバー設定更新すんねん",
		"updateUserNote": "モデレーションノート更新",
		"deleteDriveFile": "ファイルをほかす",
		"deleteNote": "ノートを削除",
		"createGlobalAnnouncement": "みんなへの通告を作成したで",
		"createUserAnnouncement": "あんたらへの通告を作成したで",
		"updateGlobalAnnouncement": "みんなへの通告更新したったで",
		"updateUserAnnouncement": "あんたらへの通告更新したったで",
		"deleteGlobalAnnouncement": "みんなへの通告消したったで",
		"deleteUserAnnouncement": "あんたらへのお知らせを削除",
		"resetPassword": "パスワードをリセット",
		"suspendRemoteInstance": "リモートサーバーを止めんで",
		"unsuspendRemoteInstance": "リモートサーバーを再開すんで",
		"updateRemoteInstanceNote": "リモートサーバーのモデレーションノート更新",
		"markSensitiveDriveFile": "ファイルをセンシティブ付与",
		"unmarkSensitiveDriveFile": "ファイルをセンシティブ解除",
		"resolveAbuseReport": "苦情を解決",
		"forwardAbuseReport": "通報を転送",
		"updateAbuseReportNote": "通報のモデレーションノート更新",
		"createInvitation": "招待コード作る",
		"createAd": "広告を作んで",
		"deleteAd": "広告ほかす",
		"updateAd": "広告を更新",
		"createAvatarDecoration": "アイコンデコレーションを作成",
		"updateAvatarDecoration": "アイコンデコレーションを更新",
		"deleteAvatarDecoration": "アイコンデコレーションを削除",
		"unsetMfa": "ユーザーの二要素認証を解除",
		"unsetUserAvatar": "この子のアイコン元に戻す",
		"unsetUserBanner": "この子のバナー元に戻す",
		"createSystemWebhook": "SystemWebhookを作成",
		"updateSystemWebhook": "SystemWebhookを更新",
		"deleteSystemWebhook": "SystemWebhookを削除",
		"createAbuseReportNotificationRecipient": "通報の通知先作る",
		"updateAbuseReportNotificationRecipient": "通報の通知先更新",
		"deleteAbuseReportNotificationRecipient": "通報の通知先消す",
		"deleteAccount": "アカウント消す",
		"deletePage": "ページ消す",
		"deleteFlash": "Playをほかす",
		"deleteGalleryPost": "ギャラリーの投稿をほかす",
		"deleteChatRoom": "ダイレクトメッセージのグループを削除",
		"updateProxyAccountDescription": "プロキシアカウントの説明を更新"
	},
	"moderationLogs": "モデログ"
}
</locale>

<locale lang="json" locale="kab-KAB">
{
	"type": "Type",
	"moderator": "Moderator",
	"loadMore": "Wali ugar",
	"all": "All",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Suspended",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Password reset",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="kn-IN">
{
	"type": "Type",
	"moderator": "Moderator",
	"loadMore": "ಇನ್ನಷ್ಟು ನೋಡು",
	"all": "All",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Suspended",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Password reset",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="ko-KR">
{
	"type": "종류",
	"moderator": "모더레이터",
	"loadMore": "더 보기",
	"all": "전체",
	"moderationLogTypesLabels": {
		"clearQueue": "작업 대기열 비우기",
		"promoteQueue": "큐의 작업을 재시도",
		"createRole": "역할 생성",
		"deleteRole": "역할 삭제",
		"updateRole": "역할 수정",
		"assignRole": "역할 할당",
		"unassignRole": "역할 해제",
		"suspend": "정지",
		"unsuspend": "정지 해제",
		"addCustomEmoji": "커스텀 이모지 추가",
		"updateCustomEmoji": "커스텀 이모지 수정",
		"deleteCustomEmoji": "커스텀 이모지 삭제",
		"updateServerSettings": "서버 설정 갱신",
		"updateUserNote": "조정 기록 갱신",
		"deleteDriveFile": "파일 삭제",
		"deleteNote": "노트 삭제",
		"createGlobalAnnouncement": "전역 공지사항 생성",
		"createUserAnnouncement": "유저에게 공지사항 만들기",
		"updateGlobalAnnouncement": "모든 공지사항 수정",
		"updateUserAnnouncement": "유저의 공지사항 수정",
		"deleteGlobalAnnouncement": "모든 공지사항 삭제",
		"deleteUserAnnouncement": "유저의 공지사항 삭제",
		"resetPassword": "비밀번호 재설정",
		"suspendRemoteInstance": "리모트 서버를 정지",
		"unsuspendRemoteInstance": "리모트 서버의 정지를 해제",
		"updateRemoteInstanceNote": "리모트 서버의 조정 기록 갱신",
		"markSensitiveDriveFile": "파일에 열람주의를 설정",
		"unmarkSensitiveDriveFile": "파일에 열람주의를 해제",
		"resolveAbuseReport": "신고 처리",
		"forwardAbuseReport": "신고 전달",
		"updateAbuseReportNote": "신고 조정 노트 갱신",
		"createInvitation": "초대 코드 생성",
		"createAd": "광고 생성",
		"deleteAd": "광고 삭제",
		"updateAd": "광고 수정",
		"createAvatarDecoration": "아바타 장식 만들기",
		"updateAvatarDecoration": "아바타 장식 수정",
		"deleteAvatarDecoration": "아바타 장식 삭제",
		"unsetMfa": "사용자의 2단계 인증 해제",
		"unsetUserAvatar": "유저 아바타 제거",
		"unsetUserBanner": "유저 배너 제거",
		"createSystemWebhook": "SystemWebhook을 생성",
		"updateSystemWebhook": "SystemWebhook을 수정",
		"deleteSystemWebhook": "SystemWebhook을 삭제",
		"createAbuseReportNotificationRecipient": "신고 알림 수신자 생성",
		"updateAbuseReportNotificationRecipient": "신고 알림 수신자 편집",
		"deleteAbuseReportNotificationRecipient": "신고 알림 수신자 삭제",
		"deleteAccount": "계정을 삭제",
		"deletePage": "페이지를 삭제",
		"deleteFlash": "Play를 삭제",
		"deleteGalleryPost": "갤러리 게시물을 삭제",
		"deleteChatRoom": "채팅방 삭제하기",
		"updateProxyAccountDescription": "프록시 계정의 설명 업데이트"
	},
	"moderationLogs": "모더레이션 로그"
}
</locale>

<locale lang="json" locale="nl-NL">
{
	"type": "Type",
	"moderator": "Moderator",
	"loadMore": "Laad meer",
	"all": "Alle",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Opschorten",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Wachtwoord terugzetten",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderatieprotocollen"
}
</locale>

<locale lang="json" locale="no-NO">
{
	"type": "Type",
	"moderator": "Moderator",
	"loadMore": "Vis mer",
	"all": "Alle",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Suspender",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Password reset",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="pl-PL">
{
	"type": "Typ",
	"moderator": "Moderator",
	"loadMore": "Załaduj więcej",
	"all": "Wszystkie",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Zawieś",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Zresetuj hasło",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Logi moderacyjne"
}
</locale>

<locale lang="json" locale="pt-PT">
{
	"type": "Tipo",
	"moderator": "Moderador",
	"loadMore": "Carregar mais",
	"all": "Todos",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Cargo criado",
		"deleteRole": "Cargo excluído",
		"updateRole": "Cargo atualizado",
		"assignRole": "Cargo atribuído",
		"unassignRole": "Cargo removido",
		"suspend": "Suspender",
		"unsuspend": "Suspensão cancelada",
		"addCustomEmoji": "Emoji personalizado adicionado",
		"updateCustomEmoji": "Emoji personalizado atualizado",
		"deleteCustomEmoji": "Emoji personalizado removido",
		"updateServerSettings": "Configurações de servidor atualizadas",
		"updateUserNote": "Nota de moderação atualizada",
		"deleteDriveFile": "Arquivo excluído",
		"deleteNote": "Nota excluída",
		"createGlobalAnnouncement": "Anúncio global criado",
		"createUserAnnouncement": "Anúncio de usuário criado",
		"updateGlobalAnnouncement": "Anúncio global atualizado",
		"updateUserAnnouncement": "Anúncio de usuário atualizado",
		"deleteGlobalAnnouncement": "Anúncio global excluído",
		"deleteUserAnnouncement": "Anúncio de usuário excluído",
		"resetPassword": "Redefinir senha",
		"suspendRemoteInstance": "Instância remota suspensa",
		"unsuspendRemoteInstance": "Suspensão de instância remota removida",
		"updateRemoteInstanceNote": "Nota de moderação atualizada para instância remota.",
		"markSensitiveDriveFile": "Arquivo marcado como sensível",
		"unmarkSensitiveDriveFile": "Arquivo desmarcado como sensível",
		"resolveAbuseReport": "Relatório resolvido",
		"forwardAbuseReport": "Denúncia encaminhada",
		"updateAbuseReportNote": "Nota de moderação da denúncia atualizada",
		"createInvitation": "Convite gerado",
		"createAd": "Propaganda criada",
		"deleteAd": "Propaganda excluída",
		"updateAd": "Propaganda atualizada",
		"createAvatarDecoration": "Decoração de avatar criada",
		"updateAvatarDecoration": "Decoração de avatar atualizada",
		"deleteAvatarDecoration": "Decoração de avatar removida",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "Remover avatar de usuário",
		"unsetUserBanner": "Remover banner de usuário",
		"createSystemWebhook": "Criar SystemWebhook",
		"updateSystemWebhook": "Atualizar SystemWebhook",
		"deleteSystemWebhook": "Remover SystemWebhook",
		"createAbuseReportNotificationRecipient": "Criar um destinatário para relatórios de abuso",
		"updateAbuseReportNotificationRecipient": "Atualizar destinatários para relatórios de abuso",
		"deleteAbuseReportNotificationRecipient": "Remover um destinatário para relatórios de abuso",
		"deleteAccount": "Remover conta",
		"deletePage": "Remover página",
		"deleteFlash": "Remover Play",
		"deleteGalleryPost": "Remover a publicação da galeria",
		"deleteChatRoom": "Sala de Conversas Excluída",
		"updateProxyAccountDescription": "Atualizar descrição da conta de proxy"
	},
	"moderationLogs": "Logs de moderação"
}
</locale>

<locale lang="json" locale="ru-RU">
{
	"type": "Тип",
	"moderator": "Модератор",
	"loadMore": "Загрузить ещё",
	"all": "Все",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Заморозить",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Добавлено эмодзи",
		"updateCustomEmoji": "Изменено эмодзи",
		"deleteCustomEmoji": "Удалено эмодзи",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "Файл удалён",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Сброс пароля:",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Создать код приглашения",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "Создать Системный Вебхук",
		"updateSystemWebhook": "Обновить Системый Вебхук",
		"deleteSystemWebhook": "Удалить Системный Вебхук",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Удалить чат",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Журнал модерации"
}
</locale>

<locale lang="json" locale="sk-SK">
{
	"type": "Typ",
	"moderator": "Moderátor",
	"loadMore": "Zobraziť viac",
	"all": "Všetko",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Zmraziť",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Resetovať heslo",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="th-TH">
{
	"type": "รูปแบบ",
	"moderator": "ผู้ควบคุม",
	"loadMore": "แสดงเพิ่มเติม",
	"all": "ทั้งหมด",
	"moderationLogTypesLabels": {
		"clearQueue": "ล้างคิว",
		"promoteQueue": "ดันงานในคิวอีกครั้ง",
		"createRole": "สร้างบทบาทแล้ว",
		"deleteRole": "ลบบทบาทแล้ว",
		"updateRole": "อัปเดตบทบาทแล้ว",
		"assignRole": "ได้รับมอบหมายบทบาท",
		"unassignRole": "ถอดออกจากบทบาทแล้ว",
		"suspend": "ระงับ",
		"unsuspend": "เลิกระงับ",
		"addCustomEmoji": "เพิ่มเอโมจิที่กำหนดเองแล้ว",
		"updateCustomEmoji": "อัปเดตเอโมจิที่กำหนดเองแล้ว",
		"deleteCustomEmoji": "ลบเอโมจิที่กำหนดเองออกแล้ว",
		"updateServerSettings": "อัปเดตการตั้งค่าเซิร์ฟเวอร์แล้ว",
		"updateUserNote": "อัปเดตโน้ตการกลั่นกรองแล้ว",
		"deleteDriveFile": "ลบไฟล์ออกแล้ว",
		"deleteNote": "ลบโน้ตออกแล้ว",
		"createGlobalAnnouncement": "สร้างประกาศทั่วโลกแล้ว",
		"createUserAnnouncement": "สร้างประกาศผู้ใช้แล้ว",
		"updateGlobalAnnouncement": "อัปเดตประกาศทั่วโลกแล้ว",
		"updateUserAnnouncement": "อัปเดตประกาศผู้ใช้แล้ว",
		"deleteGlobalAnnouncement": "ลบประกาศทั่วโลกออกแล้ว",
		"deleteUserAnnouncement": "ลบประกาศผู้ใช้ออกแล้ว",
		"resetPassword": "รีเซ็ตรหัสผ่าน",
		"suspendRemoteInstance": "ระงับเซิร์ฟเวอร์ระยะไกล",
		"unsuspendRemoteInstance": "เลิกระงับเซิร์ฟเวอร์ระยะไกล",
		"updateRemoteInstanceNote": "อัปเดตโน้ตการกลั่นกรองสำหรับเซิร์ฟเวอร์ระยะไกลแล้ว",
		"markSensitiveDriveFile": "ทำเครื่องหมายไฟล์ว่ามีเนื้อหาละเอียดอ่อน",
		"unmarkSensitiveDriveFile": "ยกเลิกทำเครื่องหมายไฟล์ว่ามีเนื้อหาละเอียดอ่อน",
		"resolveAbuseReport": "รายงานได้รับการแก้ไขแล้ว",
		"forwardAbuseReport": "ได้ส่งรายงานไปแล้ว",
		"updateAbuseReportNote": "โน้ตการกลั่นกรองที่รายงานไปนั้น ได้รับการอัปเดตแล้ว",
		"createInvitation": "สร้างรหัสเชิญ",
		"createAd": "สร้างโฆษณาแล้ว",
		"deleteAd": "ลบโฆษณาออกแล้ว",
		"updateAd": "อัปเดตโฆษณาแล้ว",
		"createAvatarDecoration": "สร้างของตกแต่งไอคอนแล้ว",
		"updateAvatarDecoration": "อัปเดตของตกแต่งไอคอนแล้ว",
		"deleteAvatarDecoration": "ลบของตกแต่งไอคอนแล้ว",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "เลิกตั้งไอคอนประจำตัวแล้ว",
		"unsetUserBanner": "ลบแบนเนอร์ผู้ใช้",
		"createSystemWebhook": "สร้าง SystemWebhook",
		"updateSystemWebhook": "อัปเดต SystemWebhook",
		"deleteSystemWebhook": "ลบ SystemWebhook",
		"createAbuseReportNotificationRecipient": "สร้างปลายทางการแจ้งเตือนการรายงาน",
		"updateAbuseReportNotificationRecipient": "อัปเดตปลายทางการแจ้งเตือนการรายงาน",
		"deleteAbuseReportNotificationRecipient": "ลบปลายทางการแจ้งเตือนการรายงาน",
		"deleteAccount": "บัญชีถูกลบไปแล้ว",
		"deletePage": "เพจถูกลบออกไปแล้ว",
		"deleteFlash": "Play ถูกลบออกไปแล้ว",
		"deleteGalleryPost": "โพสต์แกลเลอรี่ถูกลบออกแล้ว",
		"deleteChatRoom": "ลบห้องแชต",
		"updateProxyAccountDescription": "อัปเดตคำอธิบายของบัญชีพร็อกซี"
	},
	"moderationLogs": "ปูมการควบคุมดูแล"
}
</locale>

<locale lang="json" locale="tr-TR">
{
	"type": "Tür",
	"moderator": "Moderatör",
	"loadMore": "Daha fazla yükle",
	"all": "Tümü",
	"moderationLogTypesLabels": {
		"clearQueue": "Kuyruğu temizle",
		"promoteQueue": "Sıraya alınmış işi yeniden deneyin.",
		"createRole": "Rol oluşturuldu",
		"deleteRole": "Rol silindi",
		"updateRole": "Rol güncellendi",
		"assignRole": "Rol atandı",
		"unassignRole": "Görevinden alınmış",
		"suspend": "Askıya alınmış",
		"unsuspend": "Askıya alınmamış",
		"addCustomEmoji": "Özel emoji eklendi",
		"updateCustomEmoji": "Özel emoji güncellendi",
		"deleteCustomEmoji": "Özel emoji silindi",
		"updateServerSettings": "Sunucu ayarları güncellendi",
		"updateUserNote": "Moderasyon notu güncellendi",
		"deleteDriveFile": "Dosya silindi",
		"deleteNote": "Not silindi",
		"createGlobalAnnouncement": "Global duyuru oluşturuldu",
		"createUserAnnouncement": "Kullanıcı duyurusu oluşturuldu",
		"updateGlobalAnnouncement": "Global duyuru güncellendi",
		"updateUserAnnouncement": "Kullanıcı duyurusu güncellendi",
		"deleteGlobalAnnouncement": "Global duyuru silindi",
		"deleteUserAnnouncement": "Kullanıcı duyurusu silindi",
		"resetPassword": "Şifreyi sıfırla",
		"suspendRemoteInstance": "Uzak sunucu askıya alındı",
		"unsuspendRemoteInstance": "Uzak sunucu askıya alınmadı",
		"updateRemoteInstanceNote": "Uzak sunucular için güncellenmiş moderasyon notu",
		"markSensitiveDriveFile": "Hassas olarak işaretlenmiş dosya",
		"unmarkSensitiveDriveFile": "Dosya hassas olarak işaretlenmemiş",
		"resolveAbuseReport": "Rapor çözüldü",
		"forwardAbuseReport": "Rapor iletildi",
		"updateAbuseReportNote": "Güncellenen raporun moderasyon notu",
		"createInvitation": "Davet oluşturuldu",
		"createAd": "Reklam oluşturuldu",
		"deleteAd": "Reklam silindi",
		"updateAd": "Reklam güncellendi",
		"createAvatarDecoration": "Avatar dekorasyonu oluşturuldu",
		"updateAvatarDecoration": "Avatar dekorasyonu güncellendi",
		"deleteAvatarDecoration": "Avatar süsü silindi",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "Kullanıcı avatarı ayarlanmamış",
		"unsetUserBanner": "Kullanıcı başlığı ayarlanmamış",
		"createSystemWebhook": "Sistem Webhook oluşturuldu",
		"updateSystemWebhook": "Sistem Webhook güncellendi",
		"deleteSystemWebhook": "Sistem Webhook silindi",
		"createAbuseReportNotificationRecipient": "Oluşturulan raporlar için alıcı",
		"updateAbuseReportNotificationRecipient": "Raporlar için alıcı güncellendi",
		"deleteAbuseReportNotificationRecipient": "Silinen raporlar için alıcı",
		"deleteAccount": "Hesap silindi",
		"deletePage": "Sayfa silindi",
		"deleteFlash": "Oyun silindi",
		"deleteGalleryPost": "Galeri gönderisi silindi",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Proxy hesabının açıklamasını güncelle"
	},
	"moderationLogs": "Moderasyon günlükleri"
}
</locale>

<locale lang="json" locale="ug-CN">
{
	"type": "Type",
	"moderator": "Moderator",
	"loadMore": "Load more",
	"all": "All",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Suspended",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Password reset",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Invite generated",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Moderation logs"
}
</locale>

<locale lang="json" locale="uk-UA">
{
	"type": "Тип",
	"moderator": "Модератор",
	"loadMore": "Показати більше",
	"all": "Всі",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Role created",
		"deleteRole": "Role deleted",
		"updateRole": "Role updated",
		"assignRole": "Assigned to role",
		"unassignRole": "Removed from role",
		"suspend": "Призупинити",
		"unsuspend": "Unsuspended",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Скинути пароль",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Створити запрошення",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Журнали модерації"
}
</locale>

<locale lang="json" locale="vi-VN">
{
	"type": "Loại",
	"moderator": "Kiểm duyệt viên",
	"loadMore": "Tải thêm",
	"all": "Tất cả",
	"moderationLogTypesLabels": {
		"clearQueue": "Clear queue",
		"promoteQueue": "Promote queue",
		"createRole": "Tạo một vai trò",
		"deleteRole": "Xóa vai trò",
		"updateRole": "Cập nhật vai trò",
		"assignRole": "Chỉ định cho vai trò",
		"unassignRole": "Bỏ gán vai trò",
		"suspend": "Vô hiệu hóa",
		"unsuspend": "Rã đông",
		"addCustomEmoji": "Custom emoji added",
		"updateCustomEmoji": "Custom emoji updated",
		"deleteCustomEmoji": "Custom emoji deleted",
		"updateServerSettings": "Server settings updated",
		"updateUserNote": "Moderation note updated",
		"deleteDriveFile": "File deleted",
		"deleteNote": "Note deleted",
		"createGlobalAnnouncement": "Global announcement created",
		"createUserAnnouncement": "User announcement created",
		"updateGlobalAnnouncement": "Global announcement updated",
		"updateUserAnnouncement": "User announcement updated",
		"deleteGlobalAnnouncement": "Global announcement deleted",
		"deleteUserAnnouncement": "User announcement deleted",
		"resetPassword": "Đặt lại mật khẩu",
		"suspendRemoteInstance": "Remote instance suspended",
		"unsuspendRemoteInstance": "Remote instance unsuspended",
		"updateRemoteInstanceNote": "Updated moderation note for remote servers",
		"markSensitiveDriveFile": "File marked as sensitive",
		"unmarkSensitiveDriveFile": "File unmarked as sensitive",
		"resolveAbuseReport": "Report resolved",
		"forwardAbuseReport": "Report forwarded",
		"updateAbuseReportNote": "Moderation note of a report updated",
		"createInvitation": "Tạo lời mời",
		"createAd": "Ad created",
		"deleteAd": "Ad deleted",
		"updateAd": "Ad updated",
		"createAvatarDecoration": "Avatar decoration created",
		"updateAvatarDecoration": "Avatar decoration updated",
		"deleteAvatarDecoration": "Avatar decoration deleted",
		"unsetMfa": "Reset two-factor authentication for the user",
		"unsetUserAvatar": "User avatar unset",
		"unsetUserBanner": "User banner unset",
		"createSystemWebhook": "System Webhook created",
		"updateSystemWebhook": "System Webhook updated",
		"deleteSystemWebhook": "System Webhook deleted",
		"createAbuseReportNotificationRecipient": "Recipient for reports created",
		"updateAbuseReportNotificationRecipient": "Recipient for reports updated",
		"deleteAbuseReportNotificationRecipient": "Recipient for reports deleted",
		"deleteAccount": "Account deleted",
		"deletePage": "Page deleted",
		"deleteFlash": "Play deleted",
		"deleteGalleryPost": "Gallery post deleted",
		"deleteChatRoom": "Deleted Chat Room",
		"updateProxyAccountDescription": "Update the description of the proxy account"
	},
	"moderationLogs": "Nhật kí quản trị"
}
</locale>

<locale lang="json" locale="zh-CN">
{
	"type": "类型",
	"moderator": "监察员",
	"loadMore": "查看更多",
	"all": "全部",
	"moderationLogTypesLabels": {
		"clearQueue": "清除队列",
		"promoteQueue": "重新执行队列中的任务",
		"createRole": "创建角色",
		"deleteRole": "删除角色",
		"updateRole": "更新角色",
		"assignRole": "分配角色",
		"unassignRole": "取消分配角色",
		"suspend": "冻结",
		"unsuspend": "解除冻结",
		"addCustomEmoji": "添加自定义表情符号",
		"updateCustomEmoji": "更新自定义表情符号",
		"deleteCustomEmoji": "删除自定义表情符号",
		"updateServerSettings": "更新服务器设置",
		"updateUserNote": "更新管理笔记",
		"deleteDriveFile": "删除文件",
		"deleteNote": "删除帖子",
		"createGlobalAnnouncement": "创建全体通知",
		"createUserAnnouncement": "创建用户通知",
		"updateGlobalAnnouncement": "更新全体通知",
		"updateUserAnnouncement": "更新用户通知",
		"deleteGlobalAnnouncement": "删除全体通知",
		"deleteUserAnnouncement": "删除用户通知",
		"resetPassword": "重置密码",
		"suspendRemoteInstance": "停止远程服务器",
		"unsuspendRemoteInstance": "恢复远程服务器",
		"updateRemoteInstanceNote": "更新远程服务器的管理笔记",
		"markSensitiveDriveFile": "标记为敏感内容",
		"unmarkSensitiveDriveFile": "取消标记为敏感内容",
		"resolveAbuseReport": "处理举报",
		"forwardAbuseReport": "转发举报",
		"updateAbuseReportNote": "更新举报用管理笔记",
		"createInvitation": "生成邀请码",
		"createAd": "创建了广告",
		"deleteAd": "删除了广告",
		"updateAd": "更新了广告",
		"createAvatarDecoration": "新建头像挂件",
		"updateAvatarDecoration": "更新头像挂件",
		"deleteAvatarDecoration": "删除头像挂件",
		"unsetMfa": "解除用户的双重认证",
		"unsetUserAvatar": "清除用户头像",
		"unsetUserBanner": "清除用户横幅",
		"createSystemWebhook": "新建了 SystemWebhook",
		"updateSystemWebhook": "更新了 SystemWebhook",
		"deleteSystemWebhook": "删除了 SystemWebhook",
		"createAbuseReportNotificationRecipient": "新建了举报通知",
		"updateAbuseReportNotificationRecipient": "更新了举报通知",
		"deleteAbuseReportNotificationRecipient": "删除了举报通知",
		"deleteAccount": "删除帐户",
		"deletePage": "删除页面",
		"deleteFlash": "删除 Play",
		"deleteGalleryPost": "删除相册内容",
		"deleteChatRoom": "删除群聊",
		"updateProxyAccountDescription": "更新代理账户的简介"
	},
	"moderationLogs": "管理日志"
}
</locale>

<locale lang="json" locale="zh-TW">
{
	"type": "類型",
	"moderator": "審查員",
	"loadMore": "載入更多",
	"all": "全部",
	"moderationLogTypesLabels": {
		"clearQueue": "清除佇列",
		"promoteQueue": "重新嘗試排程中的工作",
		"createRole": "新增角色",
		"deleteRole": "刪除角色 ",
		"updateRole": "更新角色設定",
		"assignRole": "指派角色",
		"unassignRole": "撤銷角色",
		"suspend": "凍結",
		"unsuspend": "解除凍結",
		"addCustomEmoji": "新增自訂表情符號",
		"updateCustomEmoji": "更新自訂表情符號",
		"deleteCustomEmoji": "刪除自訂表情符號",
		"updateServerSettings": "更新伺服器設定",
		"updateUserNote": "更新了使用者的管理筆記",
		"deleteDriveFile": "刪除檔案",
		"deleteNote": "刪除貼文",
		"createGlobalAnnouncement": "建立全網通知",
		"createUserAnnouncement": "建立使用者通知",
		"updateGlobalAnnouncement": "更新全部的公告",
		"updateUserAnnouncement": "更新使用者的公告",
		"deleteGlobalAnnouncement": "刪除全部的公告",
		"deleteUserAnnouncement": "刪除使用者的公告",
		"resetPassword": "重設密碼",
		"suspendRemoteInstance": "封鎖遠端伺服器",
		"unsuspendRemoteInstance": "解除封鎖遠端伺服器",
		"updateRemoteInstanceNote": "更新了遠端伺服器的管理筆記",
		"markSensitiveDriveFile": "標記為敏感檔案",
		"unmarkSensitiveDriveFile": "撤銷標記為敏感檔案",
		"resolveAbuseReport": "解決檢舉",
		"forwardAbuseReport": "轉發檢舉",
		"updateAbuseReportNote": "更新檢舉的審查備註",
		"createInvitation": "建立邀請碼",
		"createAd": "建立廣告",
		"deleteAd": "刪除廣告",
		"updateAd": "更新廣告",
		"createAvatarDecoration": "建立頭像裝飾",
		"updateAvatarDecoration": "更新頭像裝飾",
		"deleteAvatarDecoration": "刪除頭像裝飾",
		"unsetMfa": "解除使用者的雙重驗證",
		"unsetUserAvatar": "移除使用者的大頭貼",
		"unsetUserBanner": "移除使用者的橫幅圖像",
		"createSystemWebhook": "建立 SystemWebhook",
		"updateSystemWebhook": "更新 SystemWebhook",
		"deleteSystemWebhook": "刪除 SystemWebhook",
		"createAbuseReportNotificationRecipient": "建立接收檢舉的通知對象",
		"updateAbuseReportNotificationRecipient": "更新接收檢舉的通知對象",
		"deleteAbuseReportNotificationRecipient": "刪除接收檢舉的通知對象",
		"deleteAccount": "刪除帳戶",
		"deletePage": "刪除頁面",
		"deleteFlash": "刪除 Play",
		"deleteGalleryPost": "刪除相簿的貼文",
		"deleteChatRoom": "刪除聊天室",
		"updateProxyAccountDescription": "更新代理帳戶的說明"
	},
	"moderationLogs": "管理日誌"
}
</locale>
