name: API report (misskey.js)

on:
  push:
    paths:
      - packages/misskey-js/**
      - packages/features/**
      - pnpm-lock.yaml
      - .github/workflows/api-misskey-js.yml
  pull_request:
    branches-ignore:
      - master
    paths:
      - packages/misskey-js/**
      - packages/features/**
      - pnpm-lock.yaml
      - .github/workflows/api-misskey-js.yml
jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter misskey-js build

      - name: Check files
        run: ls packages/misskey-js/built

      - name: SDK tests
        run: pnpm --filter misskey-js test
        env:
          CI: true

      - name: API report
        run: pnpm --filter misskey-js api-prod

      - name: Show report
        if: always()
        run: |
          if [ -f packages/misskey-js/temp/misskey-js.api.md ]; then
            cat packages/misskey-js/temp/misskey-js.api.md
          fi
